package com.projectdark.mobile;

import com.projectdark.mobile.world.WorldMoveTargetController;

/** Package-level contract audit for the four-way attack presentation. */
public final class AttackPresentationPackageAudit {
  public static final float MAX_FOOT_ERROR_PX=1f;
  public static final float MAX_HANDLE_ERROR_PX=1f;
  private static final int[] BODY_OFFSET_X={8,2,6,4},BODY_OFFSET_Y={8,8,9,3};
  private static final int[] ROBE_OFFSET_X={8,3,6,6},ROBE_OFFSET_Y={20,27,23,22};
  private AttackPresentationPackageAudit(){}
  public static boolean run(){return canonicalFacingFourWays()&&coherentCompositionFourWays()&&temporalPolicy()&&finalCompositeNormalizationContract()&&coherentLayerTransformFourWays()&&singleMirrorWeaponContract();}
  static boolean canonicalFacingFourWays(){float ax=320f,ay=240f;for(WorldMoveTargetController.Direction d:WorldMoveTargetController.Direction.values()){float tx=ax+d.dx,ty=ay+d.dy;if(!CanonicalMeleeTileContract.reachable(ax,ay,tx,ty))return false;CharacterRenderer.Direction expected=CanonicalMeleeTileContract.facing(d);if(expected==null||CanonicalMeleeTileContract.facing(ax,ay,tx,ty)!=expected)return false;CanonicalActorFacing facing=new CanonicalActorFacing(CharacterRenderer.Direction.SW);facing.beginAttack(d);if(!facing.attackLocked()||facing.presentation()!=expected)return false;facing.updateLocomotion(-d.dx,-d.dy);if(facing.presentation()!=expected)return false;facing.endAttack();}return true;}
  static boolean coherentCompositionFourWays(){String robe=CharacterVisualBinding.RESOLVED_SHIRT_APPEARANCE_ID,weapon=CharacterVisualBinding.RESOLVED_WEAPON_APPEARANCE_ID;for(CharacterRenderer.Direction d:CharacterRenderer.Direction.values()){CharacterRenderer.AttackVisualComposition c=CharacterRenderer.attackVisualComposition(d,robe,weapon);if(c.direction!=d||c.sourceIndex!=CharacterRenderer.actionSourceIndex(d)||!c.robeVisible||!c.weaponVisible||c.mirrorBody!=CharacterRenderer.bodyMirrorX(d))return false;}return true;}
  static boolean temporalPolicy(){return CharacterRenderer.attackUsesSinglePosePlaceholder()&&!CharacterRenderer.attackTemporalSourceResolved()&&!CharacterRenderer.attackUsesDestructiveCrop()&&CharacterRenderer.attackUsesActionPose(.50f)&&!CharacterRenderer.attackUsesActionPose(.05f)&&!CharacterRenderer.attackUsesActionPose(.95f)&&AttackTimeline.phase(.10f)==AttackTimeline.Phase.ANTICIPATION&&AttackTimeline.phase(.50f)==AttackTimeline.Phase.CONTACT&&AttackTimeline.phase(.90f)==AttackTimeline.Phase.RECOVERY&&AttackTimeline.hitCrossed(.40f,.50f);}
  static boolean finalCompositeNormalizationContract(){float base=CharacterRenderer.SOURCE_PRESENTATION_SCALE;int idleTop=8,idleBottom=45;float idleCenter=18f,expectedHeight=(idleBottom-idleTop+1)*base,expectedFoot=240f-CharacterRenderer.SOURCE_FOOT_ANCHOR_Y*base+idleBottom*base,expectedCenter=320f+(idleCenter-CharacterRenderer.SOURCE_FOOT_ANCHOR_X)*base;int[][] action={{0,50},{1,51},{0,50},{0,48}};float[] centers={8.5f,9f,9.5f,10.5f};for(int i=0;i<action.length;i++){AttackCompositeTransform.Result r=AttackCompositeTransform.normalize(320f,240f,base,CharacterRenderer.SOURCE_FOOT_ANCHOR_Y,CharacterRenderer.SOURCE_FOOT_ANCHOR_X,idleTop,idleBottom,idleCenter,action[i][0],action[i][1],centers[i]);if(!AttackCompositeTransform.finalGeometryWithinTolerance(r,action[i][0],action[i][1],centers[i],expectedHeight,expectedFoot,expectedCenter))return false;}return true;}
  static boolean coherentLayerTransformFourWays(){int[][] action={{0,50},{1,51},{0,50},{0,48}};float[] centers={8.5f,9f,9.5f,10.5f};for(CharacterRenderer.Direction d:CharacterRenderer.Direction.values()){int source=CharacterRenderer.actionSourceIndex(d);if(source<0||source>=4)return false;AttackCompositeTransform.Result r=AttackCompositeTransform.normalize(320f,240f,CharacterRenderer.SOURCE_PRESENTATION_SCALE,CharacterRenderer.SOURCE_FOOT_ANCHOR_Y,CharacterRenderer.SOURCE_FOOT_ANCHOR_X,8,45,18f,action[source][0],action[source][1],centers[source]);if(!AttackCompositeTransform.coherentLayerTransform(r,BODY_OFFSET_X[source],BODY_OFFSET_Y[source],ROBE_OFFSET_X[source],ROBE_OFFSET_Y[source],0f,0f,centers[source],action[source][1]-8f,CharacterRenderer.bodyMirrorX(d)))return false;}return true;}
  static boolean singleMirrorWeaponContract(){return CharacterRenderer.weaponTransformUsesSingleMirror();}
}
