package com.projectdark.mobile;
import com.projectdark.mobile.world.*;
import java.util.*;
/** Stable per-spawn IDs and admitted species profiles. New HP/placement values are ADAPTED. */
public final class CampaignMonsters {
 // A/B/C are the hunting areas. D contains only the single adapted final encounter.
 private static final String[][] POOLS={{"POTE_RED","POTE_GREEN","POTE_PURPLE","POTE_SILVER"},{"POTE_TREANT","POTE_ANTLION","POTE_GNOLL","POTE_LYCAN"},{"POTE_WOLFRIDER","POTE_ANTGIANT","POTE_SILVERWOLF","POTE_SPIRIT"},{"POTE_MANTIS"}};
 public static List<RuntimeState.Monster> spawn(int zone){if(zone<1||zone>4)return new ArrayList<>();String mapId=zone==4?CampaignWorld.BOSS_D:"MAP_POTE_0"+zone;return spawnOnMap(zone,mapId);}
 public static List<RuntimeState.Monster> spawnForMap(String mapId){if("MAP_POTE_04".equals(mapId))return spawnOnMap(3,mapId);return spawnOnMap(CampaignWorld.zone(mapId),mapId);}
 private static List<RuntimeState.Monster> spawnOnMap(int zone,String mapId){List<RuntimeState.Monster> out=new ArrayList<>();if(zone<1||zone>4)return out;PoteCampaignMapDef def=PoteCampaignMapDef.forId(mapId);PoteMonsterRoster roster=new PoteMonsterRoster();List<WorldMoveTargetController.TileCenter> tiles=CampaignWorld.connectedTiles(mapId);Set<String> centers=new HashSet<>();for(WorldMoveTargetController.TileCenter t:tiles)centers.add(Math.round(t.x)+":"+Math.round(t.y));String[] ids=POOLS[zone-1];
  if(zone==4){WorldMoveTargetController.TileCenter at=def.nearest((def.minX+def.maxX)*.62f,(def.minY+def.maxY)*.50f);PoteMonsterRoster.Entry e=roster.find(ids[0]);if(e==null)throw new IllegalStateException("Campaign roster is missing "+ids[0]);RuntimeState.Monster boss=new RuntimeState.Monster("POTE_MANTIS#0",e.name,at.x,at.y,3200,"B/ADAPTED_BOSS_GENERATED_CANDIDATE");boss.campaignRewardProfileId="POTE_MANTIS";boss.respawnSeconds=Float.POSITIVE_INFINITY;out.add(boss);return out;}
  List<WorldMoveTargetController.TileCenter> clear=new ArrayList<>();for(WorldMoveTargetController.TileCenter t:tiles){boolean open=true;for(WorldMoveTargetController.Direction direction:WorldMoveTargetController.Direction.values())if(!centers.contains(Math.round(t.x+direction.dx)+":"+Math.round(t.y+direction.dy))){open=false;break;}float dx=t.x-def.entryX,dy=t.y-def.entryY;if(open&&dx*dx+dy*dy>=10000)clear.add(t);}
  for(int i=0;i<new int[]{72,96,108}[zone-1];i++){String species=ids[i%ids.length];WorldMoveTargetController.TileCenter pick=null;float best=Float.MAX_VALUE;float left=def.minX+260,right=def.maxX-260,tx=left+(i%12)*(right-left)/11f,ty=def.minY+260+(i/12)*(def.maxY-def.minY-520)/(new int[]{6,8,9}[zone-1]-1f);for(WorldMoveTargetController.TileCenter t:clear){boolean near=false;for(RuntimeState.Monster m:out)if((t.x-m.x)*(t.x-m.x)+(t.y-m.y)*(t.y-m.y)<8100){near=true;break;}if(near)continue;float d=(t.x-tx)*(t.x-tx)+(t.y-ty)*(t.y-ty);if(d<best){best=d;pick=t;}}if(pick==null)throw new IllegalStateException("Campaign spawn clearance on "+mapId);PoteMonsterRoster.Entry e=roster.find(species);if(e==null)throw new IllegalStateException("Campaign roster is missing "+species);int hp=new int[]{240,450,800,1200}[zone-1];RuntimeState.Monster m=new RuntimeState.Monster(species+"#"+("POTE_SPIRIT".equals(species)?i/ids.length:i),e.name,pick.x,pick.y,hp,"B/ADAPTED_CAMPAIGN; retained candidate sprite");m.campaignRewardProfileId=species;m.respawnSeconds=6+(i%3);out.add(m);}
  return out;
 }
 private CampaignMonsters(){}
}
