package com.projectdark.mobile;

import android.content.Context;
import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Rect;
import android.graphics.RectF;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/** Crash-safe renderer for the source-derived old-Dark-Ages peasant base-body atlas. */
public final class CharacterRenderer {
  public static final String EVIDENCE="LOD_DRESSUP_HAR_MM001_MALE_BASE_BODY+ADAPTED";
  public static final String ASSET_STATUS="PRODUCTION_WEBP_IDLE_WALK_ACTIVE";
  public static final String PRESENTATION_PROFILE="PEASANT_MM001_BASE_20260916_R10_ATTACK_COMPOSITE";
  public static final String STARTER_ARCHETYPE="PEASANT";
  public static final String STARTER_CLASS_STATE="PRE_CLASS";
  public static final String IDLE_WALK_ASSET_ID="player.peasant.mm001.idle_walk.production-2026-09-12";
  public static final String IDLE_WALK_RESOURCE="player_peasant_idle_walk";
    public static final String STARTER_SHIRT_RESOURCE="player_shirt_mu0000001_source"; // exact mu0000001 wearable source atlas
  public static final String LUERS_ROBE_RESOURCE="player_armor_mu0000058_idle_walk";
  public static final String MOKDO_RESOURCE="player_weapon_mw001";
  public static final String ACTION_SOURCE_EVIDENCE="mm001 group 02 source pixels; ADAPTED PLAYTEST ACTION GROUP";
  public static final String ACTION_TEMPORAL_STATUS="SINGLE_POSE_PLACEHOLDER";
  public static final String ACTION_TEMPORAL_EVIDENCE="SINGLE_POSE_PLACEHOLDER remains UNRESOLVED; runtime uses one directional source action pose as contact while wind-up and recovery use the standing equipped paper doll without fabricated intermediate frames";
  public static final String WEAPON_SOURCE_EVIDENCE="mw001 목도 HAR/source pixels; source-derived BODY dominantHand attachment";
  public static final String ATTACK_PRESENTATION_EVIDENCE="SOURCE_DIRECTIONAL_ACTION_CONTACT: startup/recovery use equipped idle paper doll; CONTACT uses one normalized BODY+garment+mw001 composite transform with four-way authored registration";
  public static final String ATTACK_DIRECTION_EVIDENCE="runtime Pose.direction selects one locked 4-way attack direction; BODY+robe+weapon consume it unchanged";
  public static final String PAPER_DOLL_ATTACK_EVIDENCE="ATTACK consumes current equipmentVisualRef and weaponVisualRef; no baked equipment";
  public static final String ATTACK_FALLBACK_EVIDENCE="stable equipped source paper doll remains fallback when action resources/geometry are unavailable; weapon-only attack animation is unreachable";
  public static final String ATTACK_GEOMETRY_EVIDENCE="CONTACT uses 1.70 presentation scale and shares one final foot/center transform across BODY+garment+weapon; no destructive action crop";
  public static final String ROBE_ATTACK_EVIDENCE="equipped FULL_BODY mu0000058 is composited atomically with BODY during contact; UPPER mu0000001 uses its exact recovered source atlas and source registration";
  public static final String ROBE_WALK_EVIDENCE="NW/NE retain accepted registration exactly; SW/SE packaged alpha pixels remain untouched and use shared-atlas zero translation without runtime alpha re-centering";
  public static final String WEAPON_TRANSFORM_EVIDENCE="mw001 local handle (2,4) attaches directly to action BODY dominantHand through the same normalized CONTACT transform; four-way grip correction and fixed wrist-aligned angle only, no time-based independent swing";
  public static final String HIT_POSE_EVIDENCE="HIT/HURT/FLINCH character pose is disabled; source paper doll remains visually stable while damage feedback is external";

  public static final float SOURCE_BAKED_SCALE=1.50f;
  public static final float PLAYER_RENDER_SCALE=1.70f;
  public static final float SOURCE_PRESENTATION_SCALE=PLAYER_RENDER_SCALE/SOURCE_BAKED_SCALE;
  public static final float SHADOW_RENDER_SCALE=0.72f;
  public static final float LOGICAL_FOOT_ANCHOR_Y=0f;
  public static final float BASE_HEIGHT=32f;
  public static final float HEAD_TO_BODY_RATIO=0.28f;
  public static final float WALK_FRAME_SECONDS=.12f;
  public static final float WALK_CYCLE_SECONDS=WALK_FRAME_SECONDS*4f;
  public static final float WALK_FRAMES_PER_SECOND=1f/WALK_FRAME_SECONDS;
  public static final float ATTACK_ACTION_BEGIN=.18f;
  public static final float ATTACK_ACTION_END=.62f;
  public static final float ATTACK_RECOVERY_BEGIN=.62f;
  public static final boolean HARD_PIXEL_GRID=true;
  public static final boolean STARTER_WEAPONLESS=true;
  public static final boolean STARTER_OFFHAND_EMPTY=true;
  public static final boolean LEGACY_MARTIAL_ASSET_ALLOWED=false;
  public static final int MAX_ALPHA_HEIGHT_ERROR_PX=1;
  public static final int MAX_ALPHA_FOOT_ERROR_PX=1;
  public static final int MAX_ALPHA_CENTER_ERROR_PX=2;
  public static final float WEAPON_HANDLE_X=2f;
  public static final float WEAPON_HANDLE_Y=4f;

  public static final int ATLAS_FRAME_WIDTH=24,ATLAS_FRAME_HEIGHT=32,SOURCE_FRAME_WIDTH=36,SOURCE_FRAME_HEIGHT=48,SOURCE_FOOT_ANCHOR_X=18,SOURCE_FOOT_ANCHOR_Y=46,IDLE_WALK_COLUMNS=5,ATTACK_COLUMNS=4,ATLAS_ROWS=4;
  public static final int IDLE_WALK_WIDTH=ATLAS_FRAME_WIDTH*IDLE_WALK_COLUMNS,ACTION_WIDTH=ATLAS_FRAME_WIDTH*ATTACK_COLUMNS,ATLAS_HEIGHT=ATLAS_FRAME_HEIGHT*ATLAS_ROWS,SOURCE_IDLE_WALK_WIDTH=SOURCE_FRAME_WIDTH*IDLE_WALK_COLUMNS,SOURCE_ATLAS_HEIGHT=SOURCE_FRAME_HEIGHT*ATLAS_ROWS,SOURCE_ACTION_COUNT=4,ATTACK_TRAIL_GHOSTS=0;
  private static final int[] BODY_ACTION_WIDTH={17,18,19,21},BODY_ACTION_HEIGHT={51,52,51,49},BODY_ACTION_OFFSET_X={8,2,6,4},BODY_ACTION_OFFSET_Y={8,8,9,3};
  private static final float[] BODY_ACTION_PIVOT_X={8.5f,9f,9.5f,10.5f},BODY_ACTION_FOOT_Y={50f,51f,50f,48f};
  private static final int[] ROBE_ACTION_WIDTH={14,19,15,20},ROBE_ACTION_HEIGHT={33,22,30,21},ROBE_ACTION_OFFSET_X={8,3,6,6},ROBE_ACTION_OFFSET_Y={20,27,23,22};
  private static final int[] SHIRT_ACTION_WIDTH={9,13,10,13},SHIRT_ACTION_HEIGHT={18,16,16,16};
  private static final float[][] CARRY_FRAME_X={{-6,-10,10,-6,-1},{6,10,-10,6,1},{-7,-10,10,-7,9},{7,8,8,7,7}},CARRY_FRAME_Y={{21,21,23,18,26},{21,21,23,18,26},{19,19,24,17,21},{19,20,21,20,19}},CARRY_FRAME_ANGLE={{56,62,48,59,52},{-64,-58,-72,-61,-68},{72,78,62,75,68},{-62,-64,-66,-64,-62}},ROBE_FRAME_X={{-1,-2,-1,0,1},{2,2,2,0,1},{0,0,0,0,0},{0,0,0,0,0}},ROBE_FRAME_Y={{0,0,0,0,0},{0,0,0,0,0},{0,0,0,0,0},{0,0,0,0,0}};
  private static volatile float presentationWalkClock;

  public enum Direction { NW, NE, SW, SE }
  public enum State { IDLE, WALK, CAST, ATTACK, SKILL, HIT, DEAD }
  public enum Layer { BODY, HAIR, EQUIPMENT, WEAPON, EFFECT }
  public enum EffectFamily { NONE, CAST, MAGIC, THROW, PUNCH, KICK, SKILL, HIT }
  public static final List<Layer> DRAW_ORDER=Collections.unmodifiableList(Arrays.asList(Layer.BODY,Layer.HAIR,Layer.EQUIPMENT,Layer.WEAPON,Layer.EFFECT));
  public static final List<String> PAPER_DOLL_ORDER=Collections.unmodifiableList(Arrays.asList("BODY_BASE","HAIR_STYLE","HAIR_COLOR","HEAD","FULL_BODY","UPPER","LOWER","HANDS","FEET","WEAPON","SHIELD","OFFHAND"));

  public static final class DirectionalVisualSet { public final String nw,ne,sw,se; public DirectionalVisualSet(String nw,String ne,String sw,String se){this.nw=nw;this.ne=ne;this.sw=sw;this.se=se;} public String forDirection(Direction d){if(d==null)return null;switch(d){case NW:return nw;case NE:return ne;case SW:return sw;case SE:return se;default:return null;}} public boolean unresolved(){return nw==null&&ne==null&&sw==null&&se==null;} }
  public static final class Pose { public final float x,y,walkClock,stateClock,stateDuration; public final Direction direction; public final State state; public final boolean hitFlash; public final String equipmentVisualRef,weaponVisualRef,effectVisualRef; public final EffectFamily effectFamily; public final AnimationAction animationAction; public Pose(float x,float y,Direction direction,State state,float walkClock,float stateClock,float stateDuration,boolean hitFlash,String equipmentVisualRef,String weaponVisualRef,String effectVisualRef,EffectFamily effectFamily){this(x,y,direction,state,walkClock,stateClock,stateDuration,hitFlash,equipmentVisualRef,weaponVisualRef,effectVisualRef,effectFamily,inferAnimationAction(state,effectFamily,weaponVisualRef));} public Pose(float x,float y,Direction direction,State state,float walkClock,float stateClock,float stateDuration,boolean hitFlash,String equipmentVisualRef,String weaponVisualRef,String effectVisualRef,EffectFamily effectFamily,AnimationAction animationAction){this.x=x;this.y=y;this.direction=direction;this.state=state;this.walkClock=walkClock;this.stateClock=stateClock;this.stateDuration=stateDuration;this.hitFlash=hitFlash;this.equipmentVisualRef=equipmentVisualRef;this.weaponVisualRef=weaponVisualRef;this.effectVisualRef=effectVisualRef;this.effectFamily=effectFamily==null?EffectFamily.NONE:effectFamily;this.animationAction=animationAction;} }
  public static final class AttackVisualComposition { public final Direction direction;public final int sourceIndex;public final boolean mirrorBody,weaponBehindBody,robeVisible,weaponVisible;public final float presentationScale; AttackVisualComposition(Direction direction,int sourceIndex,boolean mirrorBody,boolean weaponBehindBody,boolean robeVisible,boolean weaponVisible,float presentationScale){this.direction=direction;this.sourceIndex=sourceIndex;this.mirrorBody=mirrorBody;this.weaponBehindBody=weaponBehindBody;this.robeVisible=robeVisible;this.weaponVisible=weaponVisible;this.presentationScale=presentationScale;} public String signature(){return direction+":"+sourceIndex+":"+mirrorBody+":"+weaponBehindBody+":"+robeVisible+":"+weaponVisible+":"+weaponAttackOffsetX(direction)+":"+weaponAttackOffsetY(direction)+":"+weaponAttackAngle(direction,.55f);} }
  private static final class AlphaBounds {final int left,top,right,bottom;AlphaBounds(int left,int top,int right,int bottom){this.left=left;this.top=top;this.right=right;this.bottom=bottom;}boolean empty(){return right<left||bottom<top;}int width(){return empty()?0:right-left+1;}int height(){return empty()?0:bottom-top+1;}float centerX(){return empty()?0f:(left+right)*.5f;}}
  private static final class Registration {final float x,y;Registration(float x,float y){this.x=x;this.y=y;}}
  private static final class ActionGeometry {final int offsetX,offsetY,cropTop,cropBottomExclusive,heightError,footError,centerError;final boolean compatible;ActionGeometry(int x,int y,int cropTop,int cropBottomExclusive,int h,int f,int c,boolean ok){offsetX=x;offsetY=y;this.cropTop=cropTop;this.cropBottomExclusive=cropBottomExclusive;heightError=h;footError=f;centerError=c;compatible=ok;}}
  private final Paint pixelPaint=new Paint(),fxPaint=new Paint();
  private final Bitmap idleWalkAtlas,starterShirtSource,luersRobeAtlas,mokdoSprite; private final Bitmap[] bodyActionFrames=new Bitmap[SOURCE_ACTION_COUNT],robeActionFrames=new Bitmap[SOURCE_ACTION_COUNT],shirtActionFrames=new Bitmap[SOURCE_ACTION_COUNT];

  public CharacterRenderer(){pixelPaint.setAntiAlias(false);pixelPaint.setDither(false);pixelPaint.setFilterBitmap(false);fxPaint.setAntiAlias(false);fxPaint.setDither(false);fxPaint.setFilterBitmap(false);Resources resources=findProcessResources();idleWalkAtlas=tryLoadByName(resources,IDLE_WALK_RESOURCE,SOURCE_IDLE_WALK_WIDTH,SOURCE_ATLAS_HEIGHT);starterShirtSource=tryLoadByName(resources,STARTER_SHIRT_RESOURCE,298,19);luersRobeAtlas=tryLoadByName(resources,LUERS_ROBE_RESOURCE,SOURCE_IDLE_WALK_WIDTH,SOURCE_ATLAS_HEIGHT);mokdoSprite=tryLoadByName(resources,MOKDO_RESOURCE,16,8);for(int i=0;i<SOURCE_ACTION_COUNT;i++){bodyActionFrames[i]=tryLoadByName(resources,"player_body_mm001_action02_"+i,BODY_ACTION_WIDTH[i],BODY_ACTION_HEIGHT[i]);robeActionFrames[i]=tryLoadByName(resources,"player_robe_mu0000058_action02_"+i,ROBE_ACTION_WIDTH[i],ROBE_ACTION_HEIGHT[i]);shirtActionFrames[i]=ShirtSourceRegistration.actionFrame(starterShirtSource,i);}}
  CharacterRenderer(Bitmap idle,Bitmap shirt,Bitmap robe,Bitmap weapon,Bitmap[] bodies,Bitmap[] robes){
    idleWalkAtlas=idle;starterShirtSource=shirt;luersRobeAtlas=robe;mokdoSprite=weapon;
    pixelPaint.setFilterBitmap(false);
    for(int i=0;i<SOURCE_ACTION_COUNT;i++){bodyActionFrames[i]=bodies[i];robeActionFrames[i]=robes[i];shirtActionFrames[i]=ShirtSourceRegistration.actionFrame(shirt,i);}
  }
  public static int atlasRow(Direction direction){if(direction==null)return -1;switch(direction){case NW:return 0;case NE:return 1;case SW:return 2;case SE:return 3;default:return -1;}}
  public static Direction visualFacingForRow(int row){switch(row){case 0:return Direction.NW;case 1:return Direction.NE;case 2:return Direction.SW;case 3:return Direction.SE;default:return null;}}
  public static void setPresentationWalkClock(float clock){presentationWalkClock=Math.max(0f,clock);} public static float presentationWalkClock(){return presentationWalkClock;}
  public boolean resourceAtlasActive(){return validAtlas(idleWalkAtlas,SOURCE_IDLE_WALK_WIDTH,SOURCE_ATLAS_HEIGHT);} public boolean attackAtlasActive(){return sourceActionActive();} public boolean equipmentAtlasActive(){return starterShirtSource!=null||validAtlas(luersRobeAtlas,SOURCE_IDLE_WALK_WIDTH,SOURCE_ATLAS_HEIGHT);} public boolean weaponSourceActive(){return validAtlas(mokdoSprite,16,8);}
  public boolean sourceActionActive(){for(int i=0;i<SOURCE_ACTION_COUNT;i++)if(!validAtlas(bodyActionFrames[i],BODY_ACTION_WIDTH[i],BODY_ACTION_HEIGHT[i]))return false;return true;}
  public static boolean usesSourceActionPose(State state,AnimationAction action){return state==State.ATTACK&&action==AnimationAction.SWING;} public static boolean attackUsesActionPose(float phase){float q=Math.max(0f,Math.min(1f,phase));return q>=ATTACK_ACTION_BEGIN&&q<ATTACK_ACTION_END;}
  public static int attackThreePose(float phase){float q=Math.max(0f,Math.min(1f,phase));return q<ATTACK_ACTION_BEGIN?0:q<ATTACK_RECOVERY_BEGIN?1:2;} public static boolean attackUsesDestructiveCrop(){return false;} public static boolean attackTemporalSourceResolved(){return false;} public static boolean attackUsesSinglePosePlaceholder(){return ACTION_TEMPORAL_STATUS.equals("SINGLE_POSE_PLACEHOLDER");}
  public static int paperDollAtlasColumn(State state,float walkClock){return state==State.WALK?1+walkFrameIndex(walkClock):0;}
  public static boolean sourceActionLayersReadyContract(String equipmentVisualRef,String weaponVisualRef,boolean bodyReady,boolean robeReady,boolean weaponReady){if(!bodyReady)return false;if(containsVisualRef(equipmentVisualRef,CharacterVisualBinding.RESOLVED_LUERS_ROBE_APPEARANCE_ID)&&!robeReady)return false;if(containsVisualRef(weaponVisualRef,CharacterVisualBinding.RESOLVED_WEAPON_APPEARANCE_ID)&&!weaponReady)return false;return true;}
  public static boolean alphaGeometryWithinTolerance(int idleHeight,int actionHeight,int footError,int centerError){return idleHeight>0&&actionHeight>0&&Math.abs(idleHeight-actionHeight)<=MAX_ALPHA_HEIGHT_ERROR_PX&&Math.abs(footError)<=MAX_ALPHA_FOOT_ERROR_PX&&Math.abs(centerError)<=MAX_ALPHA_CENTER_ERROR_PX;}
  private boolean sourceActionReadyFor(Pose pose){if(pose==null)return false;int source=actionSourceIndex(pose.direction);boolean bodyReady=source>=0&&source<SOURCE_ACTION_COUNT&&validAtlas(bodyActionFrames[source],BODY_ACTION_WIDTH[source],BODY_ACTION_HEIGHT[source]);boolean robeReady=source>=0&&source<SOURCE_ACTION_COUNT&&validAtlas(robeActionFrames[source],ROBE_ACTION_WIDTH[source],ROBE_ACTION_HEIGHT[source]);boolean shirtReady=source>=0&&source<SOURCE_ACTION_COUNT&&validAtlas(shirtActionFrames[source],SHIRT_ACTION_WIDTH[source],SHIRT_ACTION_HEIGHT[source]);if(containsVisualRef(pose.equipmentVisualRef,CharacterVisualBinding.RESOLVED_SHIRT_APPEARANCE_ID)&&!shirtReady)return false;if(!sourceActionLayersReadyContract(pose.equipmentVisualRef,pose.weaponVisualRef,bodyReady,robeReady,weaponSourceActive()))return false;return actionGeometry(pose.direction,source)!=null;}
  private boolean sourcePaperDollReadyFor(Pose pose){if(pose==null||!resourceAtlasActive())return false;if(containsVisualRef(pose.equipmentVisualRef,CharacterVisualBinding.RESOLVED_SHIRT_APPEARANCE_ID)&&starterShirtSource==null)return false;if(containsVisualRef(pose.weaponVisualRef,CharacterVisualBinding.RESOLVED_WEAPON_APPEARANCE_ID)&&!weaponSourceActive())return false;return true;}

  public void draw(Canvas canvas,Pose pose){if(canvas==null||pose==null||pose.direction==null||pose.state==null)return;float anchorY=pose.y+LOGICAL_FOOT_ANCHOR_Y;drawShadow(canvas,pose,anchorY);if((pose.state==State.IDLE||pose.state==State.WALK||pose.state==State.HIT)&&sourcePaperDollReadyFor(pose)){drawSourcePaperDoll(canvas,pose,anchorY,false);return;}if(usesSourceActionPose(pose.state,pose.animationAction)&&sourceActionReadyFor(pose)){if(attackUsesActionPose(attackPhase(pose)))drawSourceAction(canvas,pose,anchorY);else if(sourcePaperDollReadyFor(pose))drawSourcePaperDoll(canvas,pose,anchorY,false);return;}if(pose.state==State.ATTACK){if(sourcePaperDollReadyFor(pose))drawSourcePaperDoll(canvas,pose,anchorY,false);return;}if(sourcePaperDollReadyFor(pose)){drawSourcePaperDoll(canvas,pose,anchorY,false);return;}drawSafePeasantFallback(canvas,pose,anchorY);}
  private void drawSourcePaperDoll(Canvas c,Pose pose,float anchorY,boolean attackingWeapon){boolean weaponBehind=weaponBehindBody(pose.direction);if(weaponBehind)drawWeapon(c,pose,anchorY,attackingWeapon);drawIdleWalk(c,pose,anchorY);drawEquipment(c,pose,anchorY);drawAccessoryEquipment(c,pose,anchorY);if(!weaponBehind)drawWeapon(c,pose,anchorY,attackingWeapon);}
  private void drawAccessoryEquipment(Canvas c,Pose pose,float anchorY){
    int row=atlasRow(pose.direction),col=paperDollAtlasColumn(pose.state,presentationWalkClock);if(row<0)return;
    float left=Math.round(pose.x-SOURCE_FOOT_ANCHOR_X*SOURCE_PRESENTATION_SCALE),top=Math.round(anchorY-SOURCE_FOOT_ANCHOR_Y*SOURCE_PRESENTATION_SCALE);
    boolean shoes=containsVisualRef(pose.equipmentVisualRef,"equip_basic_shoes"),gloves=containsVisualRef(pose.equipmentVisualRef,"equip_leather_glove");
    if(shoes){pixelPaint.setColor(0xff3a2a20);float step=(col==2?-1:col==4?1:0)*SOURCE_PRESENTATION_SCALE;float y=top+43*SOURCE_PRESENTATION_SCALE;c.drawRect(left+(7+step)*SOURCE_PRESENTATION_SCALE,y,left+(14+step)*SOURCE_PRESENTATION_SCALE,y+4*SOURCE_PRESENTATION_SCALE,pixelPaint);c.drawRect(left+(20-step)*SOURCE_PRESENTATION_SCALE,y,left+(27-step)*SOURCE_PRESENTATION_SCALE,y+4*SOURCE_PRESENTATION_SCALE,pixelPaint);}
    if(gloves){pixelPaint.setColor(0xff6b4b32);float y=top+27*SOURCE_PRESENTATION_SCALE;c.drawRect(left+3*SOURCE_PRESENTATION_SCALE,y,left+7*SOURCE_PRESENTATION_SCALE,y+5*SOURCE_PRESENTATION_SCALE,pixelPaint);c.drawRect(left+29*SOURCE_PRESENTATION_SCALE,y,left+33*SOURCE_PRESENTATION_SCALE,y+5*SOURCE_PRESENTATION_SCALE,pixelPaint);}
    pixelPaint.setColor(Color.WHITE);
  }
  private void drawShadow(Canvas c,Pose pose,float anchorY){float width=(pose.state==State.DEAD?13f:10.5f)*SHADOW_RENDER_SCALE,height=(pose.state==State.DEAD?2f:2.8f)*SHADOW_RENDER_SCALE;fxPaint.setStyle(Paint.Style.FILL);fxPaint.setColor(0x50000000);c.drawOval(new RectF(pose.x-width,anchorY-height,pose.x+width,anchorY+height),fxPaint);}
  private void drawIdleWalk(Canvas c,Pose pose,float anchorY){int row=atlasRow(pose.direction);if(row<0){drawSafePeasantFallback(c,pose,anchorY);return;}int col=paperDollAtlasColumn(pose.state,presentationWalkClock);drawAtlasCell(c,idleWalkAtlas,row,col,SOURCE_FRAME_WIDTH,SOURCE_FRAME_HEIGHT,SOURCE_FOOT_ANCHOR_X,SOURCE_FOOT_ANCHOR_Y,SOURCE_PRESENTATION_SCALE,anchorY,pose.x);}
  private void drawEquipment(Canvas c,Pose pose,float anchorY){
    int row=atlasRow(pose.direction);if(row<0)return;
    int col=paperDollAtlasColumn(pose.state,presentationWalkClock);
    if(containsVisualRef(pose.equipmentVisualRef,CharacterVisualBinding.RESOLVED_LUERS_ROBE_APPEARANCE_ID)&&luersRobeAtlas!=null){
      drawAtlasCell(c,luersRobeAtlas,row,col,SOURCE_FRAME_WIDTH,SOURCE_FRAME_HEIGHT,SOURCE_FOOT_ANCHOR_X,SOURCE_FOOT_ANCHOR_Y,SOURCE_PRESENTATION_SCALE,anchorY+ROBE_FRAME_Y[row][col],pose.x+ROBE_FRAME_X[row][col]);
    }else if(containsVisualRef(pose.equipmentVisualRef,CharacterVisualBinding.RESOLVED_SHIRT_APPEARANCE_ID)&&starterShirtSource!=null){
      int frame=ShirtSourceRegistration.idleFrame(pose.direction,col);
      AlphaBounds bounds=alphaBoundsCell(idleWalkAtlas,row,col,SOURCE_FRAME_WIDTH,SOURCE_FRAME_HEIGHT);
      float left=Math.round(pose.x-SOURCE_FOOT_ANCHOR_X*SOURCE_PRESENTATION_SCALE);
      float top=Math.round(anchorY-SOURCE_FOOT_ANCHOR_Y*SOURCE_PRESENTATION_SCALE);
      float scaleX=bounds.width()*SOURCE_PRESENTATION_SCALE/ShirtSourceRegistration.BODY_WIDTH[frame];
      float scaleY=bounds.height()*SOURCE_PRESENTATION_SCALE/ShirtSourceRegistration.BODY_HEIGHT[frame];
      left+=bounds.left*SOURCE_PRESENTATION_SCALE;top+=bounds.top*SOURCE_PRESENTATION_SCALE;
      c.save();
      if(pose.direction==Direction.NW||pose.direction==Direction.SW)c.scale(-1,1,left+bounds.width()*SOURCE_PRESENTATION_SCALE*.5f,anchorY);
      Rect src=ShirtSourceRegistration.idleRect(frame);
      float x=left+ShirtSourceRegistration.idleX(frame)*scaleX,y=top+ShirtSourceRegistration.idleY(frame)*scaleY;
      c.drawBitmap(starterShirtSource,src,new RectF(Math.round(x),Math.round(y),Math.round(x+src.width()*scaleX),Math.round(y+src.height()*scaleY)),pixelPaint);
      c.restore();
    }
  }
  /** Shared garment attachment primitive. Coverage (UPPER/FULL_BODY) controls equip conflicts, not placement math. */
  private void drawGarmentAttached(Canvas c,Bitmap bitmap,Rect src,float bodyAnchorX,float bodyAnchorY,float garmentAnchorX,float garmentAnchorY,float scale,boolean mirror){if(c==null||bitmap==null||src==null)return;float left=Math.round(bodyAnchorX-garmentAnchorX*scale),top=Math.round(bodyAnchorY-garmentAnchorY*scale);RectF dst=new RectF(left,top,Math.round(left+src.width()*scale),Math.round(top+src.height()*scale));c.save();if(mirror)c.scale(-1f,1f,bodyAnchorX,bodyAnchorY);c.drawBitmap(bitmap,src,dst,pixelPaint);c.restore();}
  private void drawGarmentAttached(Canvas c,Bitmap bitmap,float bodyAnchorX,float bodyAnchorY,float garmentAnchorX,float garmentAnchorY,float scale){if(bitmap==null)return;drawGarmentAttached(c,bitmap,new Rect(0,0,bitmap.getWidth(),bitmap.getHeight()),bodyAnchorX,bodyAnchorY,garmentAnchorX,garmentAnchorY,scale,false);}
  private Registration robeRegistration(Direction direction,int atlasColumn){int row=atlasRow(direction),col=Math.max(0,Math.min(IDLE_WALK_COLUMNS-1,atlasColumn));if(row<0)return new Registration(0f,0f);return new Registration(ROBE_FRAME_X[row][col],ROBE_FRAME_Y[row][col]);}
  public static float robeFrameRegistrationX(Direction direction,int atlasColumn){int row=atlasRow(direction),column=Math.max(0,Math.min(IDLE_WALK_COLUMNS-1,atlasColumn));return row<0?0f:ROBE_FRAME_X[row][column];} public static float robeFrameRegistrationY(Direction direction,int atlasColumn){int row=atlasRow(direction),column=Math.max(0,Math.min(IDLE_WALK_COLUMNS-1,atlasColumn));return row<0?0f:ROBE_FRAME_Y[row][column];} public static boolean robeUsesRuntimeXYRegistration(Direction direction){return direction==Direction.SW||direction==Direction.SE;}
  public static boolean robeRegistrationContinuityWithin(float maxDelta){if(maxDelta<0f)return false;for(Direction d:Direction.values())for(int col=1;col<IDLE_WALK_COLUMNS;col++){if(Math.abs(robeFrameRegistrationX(d,col)-robeFrameRegistrationX(d,col-1))>maxDelta)return false;if(Math.abs(robeFrameRegistrationY(d,col)-robeFrameRegistrationY(d,col-1))>maxDelta)return false;}return true;}
  private static boolean containsVisualRef(String refs,String expected){if(refs==null||expected==null)return false;for(String ref:refs.split(","))if(expected.equals(ref.trim()))return true;return false;}

  private void drawSourceAction(Canvas c,Pose pose,float anchorY){
    AttackVisualComposition composition=attackVisualComposition(pose.direction,pose.equipmentVisualRef,pose.weaponVisualRef);int source=composition.sourceIndex,row=atlasRow(pose.direction);if(source<0||row<0)return;
    AlphaBounds idle=alphaBoundsCell(idleWalkAtlas,row,0,SOURCE_FRAME_WIDTH,SOURCE_FRAME_HEIGHT),action=alphaBounds(bodyActionFrames[source]);
    if(idle.empty()||action.empty()){drawSourcePaperDoll(c,pose,anchorY,false);return;}
    AttackCompositeTransform.Result transform=AttackCompositeTransform.normalize(pose.x,anchorY,SOURCE_PRESENTATION_SCALE,SOURCE_FOOT_ANCHOR_Y,SOURCE_FOOT_ANCHOR_X,idle.top,idle.bottom,idle.centerX(),action.top,action.bottom,action.centerX());
    CharacterSemanticRig.Anchors body=CharacterSemanticRig.derive(bodyActionFrames[source],new Rect(0,0,BODY_ACTION_WIDTH[source],BODY_ACTION_HEIGHT[source]),pose.direction);
    if(composition.weaponVisible&&composition.weaponBehindBody)drawActionWeapon(c,pose,source,transform,body);
    c.save();if(composition.mirrorBody)c.scale(-1f,1f,transform.mirrorPivotX,anchorY);
    drawRawSourceScaled(c,bodyActionFrames[source],transform.bodyLeft,transform.bodyTop,transform.scale);
    if(containsVisualRef(pose.equipmentVisualRef,CharacterVisualBinding.RESOLVED_SHIRT_APPEARANCE_ID)){drawRawSourceScaled(c,shirtActionFrames[source],transform.bodyLeft+ShirtSourceRegistration.actionX(source)*transform.scale,transform.bodyTop+ShirtSourceRegistration.actionY(source)*transform.scale,transform.scale);}else if(composition.robeVisible){float robeLeft=transform.layerLeft(ROBE_ACTION_OFFSET_X[source],BODY_ACTION_OFFSET_X[source],0f),robeTop=transform.layerTop(ROBE_ACTION_OFFSET_Y[source],BODY_ACTION_OFFSET_Y[source],0f);float robeAnchorX=(pose.x-robeLeft)/transform.scale,robeAnchorY=(anchorY-robeTop)/transform.scale;drawGarmentAttached(c,robeActionFrames[source],pose.x,anchorY,robeAnchorX,robeAnchorY,transform.scale);}
    c.restore();if(composition.weaponVisible&&!composition.weaponBehindBody)drawActionWeapon(c,pose,source,transform,body);
  }
  private void drawActionAccessories(Canvas c,Pose pose,float anchorY){drawAccessoryEquipment(c,pose,anchorY);}\n  private void drawActionWeapon(Canvas c,Pose pose,int source,AttackCompositeTransform.Result transform,CharacterSemanticRig.Anchors body){if(!containsVisualRef(pose.weaponVisualRef,CharacterVisualBinding.RESOLVED_WEAPON_APPEARANCE_ID)||!weaponSourceActive()||source<0||source>=SOURCE_ACTION_COUNT||transform==null||body==null)return;float scale=transform.scale;float handleX=transform.handleX(actionWeaponHandX(pose.direction,body),bodyMirrorX(pose.direction)),handleY=transform.handleY(actionWeaponHandY(pose.direction,body)),angle=weaponAttackAngle(pose.direction,attackPhase(pose));c.save();c.rotate(angle,handleX,handleY);if(weaponMirrorX(pose.direction))c.scale(-1f,1f,handleX,handleY);drawRawSourceScaled(c,mokdoSprite,handleX-WEAPON_HANDLE_X*scale,handleY-WEAPON_HANDLE_Y*scale,scale);c.restore();}
  private ActionGeometry actionGeometry(Direction direction,int source){if(direction==null||source<0||source>=SOURCE_ACTION_COUNT||!resourceAtlasActive())return null;int row=atlasRow(direction);if(row<0)return null;AlphaBounds idle=alphaBoundsCell(idleWalkAtlas,row,0,SOURCE_FRAME_WIDTH,SOURCE_FRAME_HEIGHT),action=alphaBounds(bodyActionFrames[source]);if(idle.empty()||action.empty())return null;float semanticGlobalPivotX=BODY_ACTION_OFFSET_X[source]+BODY_ACTION_PIVOT_X[source],semanticGlobalFootY=BODY_ACTION_OFFSET_Y[source]+BODY_ACTION_FOOT_Y[source];int dx=Math.round(SOURCE_FOOT_ANCHOR_X-semanticGlobalPivotX),dy=Math.round(SOURCE_FOOT_ANCHOR_Y-semanticGlobalFootY),footErr=Math.abs(SOURCE_FOOT_ANCHOR_Y-Math.round(semanticGlobalFootY+dy)),centerErr=Math.round(Math.abs(SOURCE_FOOT_ANCHOR_X-(semanticGlobalPivotX+dx))),hErr=Math.abs(idle.height()-action.height());return new ActionGeometry(dx,dy,0,BODY_ACTION_HEIGHT[source],hErr,footErr,centerErr,true);}
  private static AlphaBounds alphaBounds(Bitmap bitmap){if(bitmap==null)return new AlphaBounds(0,0,-1,-1);int l=bitmap.getWidth(),t=bitmap.getHeight(),r=-1,b=-1;for(int y=0;y<bitmap.getHeight();y++)for(int x=0;x<bitmap.getWidth();x++)if(((bitmap.getPixel(x,y)>>>24)&0xff)!=0){if(x<l)l=x;if(x>r)r=x;if(y<t)t=y;if(y>b)b=y;}return new AlphaBounds(l,t,r,b);} private static AlphaBounds alphaBoundsCell(Bitmap atlas,int row,int col,int w,int h){if(atlas==null)return new AlphaBounds(0,0,-1,-1);int ox=col*w,oy=row*h,l=w,t=h,r=-1,b=-1;for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(((atlas.getPixel(ox+x,oy+y)>>>24)&0xff)!=0){if(x<l)l=x;if(x>r)r=x;if(y<t)t=y;if(y>b)b=y;}return new AlphaBounds(l,t,r,b);}
  public static float normalizedActionScale(int source){return SOURCE_PRESENTATION_SCALE;} public static int actionCanonicalVisibleHeightPixels(){return SOURCE_FRAME_HEIGHT;} public static int actionCanonicalFootAnchorPixels(){return SOURCE_FOOT_ANCHOR_Y;} public static int actionVisibleHeightPixels(int source){if(source<0||source>=SOURCE_ACTION_COUNT)return 0;return BODY_ACTION_HEIGHT[source];} public static float actionSemanticPivotX(int source){return source<0||source>=SOURCE_ACTION_COUNT?Float.NaN:BODY_ACTION_OFFSET_X[source]+BODY_ACTION_PIVOT_X[source];} public static float actionSemanticFootY(int source){return source<0||source>=SOURCE_ACTION_COUNT?Float.NaN:BODY_ACTION_OFFSET_Y[source]+BODY_ACTION_FOOT_Y[source];} public static boolean bodyMirrorX(Direction d){return d==Direction.NW||d==Direction.SW;} public static boolean weaponMirrorX(Direction d){return d==Direction.NW||d==Direction.SW;}
  public static AttackVisualComposition attackVisualComposition(Direction direction,String equipmentVisualRef,String weaponVisualRef){return new AttackVisualComposition(direction,actionSourceIndex(direction),bodyMirrorX(direction),weaponBehindBody(direction),(containsVisualRef(equipmentVisualRef,CharacterVisualBinding.RESOLVED_LUERS_ROBE_APPEARANCE_ID)||containsVisualRef(equipmentVisualRef,CharacterVisualBinding.RESOLVED_SHIRT_APPEARANCE_ID)),containsVisualRef(weaponVisualRef,CharacterVisualBinding.RESOLVED_WEAPON_APPEARANCE_ID),PLAYER_RENDER_SCALE);} public static boolean weaponBehindBody(Direction direction){return direction==Direction.NW||direction==Direction.NE;}
  private void drawWeapon(Canvas c,Pose pose,float anchorY,boolean attacking){if(!containsVisualRef(pose.weaponVisualRef,CharacterVisualBinding.RESOLVED_WEAPON_APPEARANCE_ID)||!weaponSourceActive())return;float scale=SOURCE_PRESENTATION_SCALE;int frame=paperDollAtlasColumn(pose.state,presentationWalkClock),row=atlasRow(pose.direction);if(row<0)return;int sourceColumn=attacking?0:frame;Rect cell=atlasCellRect(row,sourceColumn);float bodyLeft=Math.round(pose.x-SOURCE_FOOT_ANCHOR_X*scale),bodyTop=Math.round(anchorY-SOURCE_FOOT_ANCHOR_Y*scale);CharacterSemanticRig.Anchors body=CharacterSemanticRig.derive(idleWalkAtlas,cell,pose.direction);float handleX=bodyLeft+body.dominantHand.x*scale,handleY=bodyTop+body.dominantHand.y*scale,angle=attacking?weaponAttackAngle(pose.direction,attackPhase(pose)):weaponCarryAngle(pose.direction,frame);c.save();c.rotate(angle,handleX,handleY);if(weaponMirrorX(pose.direction))c.scale(-1f,1f,handleX,handleY);drawRawSourceScaled(c,mokdoSprite,handleX-WEAPON_HANDLE_X*scale,handleY-WEAPON_HANDLE_Y*scale,scale);c.restore();}
  private static Rect atlasCellRect(int row,int col){int left=col*SOURCE_FRAME_WIDTH,top=row*SOURCE_FRAME_HEIGHT;return new Rect(left,top,left+SOURCE_FRAME_WIDTH,top+SOURCE_FRAME_HEIGHT);} private static float attackPhase(Pose pose){if(pose==null||pose.stateDuration<=0f)return 0f;return Math.max(0f,Math.min(1f,pose.stateClock/pose.stateDuration));}
  public static float weaponCarryAngle(Direction direction){if(direction==null)return 0f;switch(direction){case NW:return 56f;case NE:return -64f;case SW:return 72f;case SE:return -62f;default:return 0f;}} public static float weaponCarryAngle(Direction direction,int atlasColumn){int row=atlasRow(direction),column=Math.max(0,Math.min(IDLE_WALK_COLUMNS-1,atlasColumn));if(row<0)return 0f;return CARRY_FRAME_ANGLE[row][column];} public static float weaponCarryOffsetX(Direction direction){if(direction==null)return 0f;switch(direction){case NW:return -7f;case NE:return 6f;case SW:return -9f;case SE:return 8f;default:return 0f;}} public static float weaponCarryOffsetX(Direction direction,int atlasColumn){return carryFrameAnchor(direction,atlasColumn,true);} public static float weaponCarryOffsetY(Direction direction){if(direction==null)return 22f;switch(direction){case NW:return 26f;case NE:return 24f;case SW:return 21f;case SE:return 23f;default:return 22f;}} public static float weaponCarryOffsetY(Direction direction,int atlasColumn){return carryFrameAnchor(direction,atlasColumn,false);} private static float carryFrameAnchor(Direction direction,int atlasColumn,boolean x){int row=atlasRow(direction),column=Math.max(0,Math.min(IDLE_WALK_COLUMNS-1,atlasColumn));if(row<0)return 0f;return x?CARRY_FRAME_X[row][column]:CARRY_FRAME_Y[row][column];}
  public static float weaponCarryMaxJumpX(Direction direction){return maxCarryJump(direction,0);} public static float weaponCarryMaxJumpY(Direction direction){return maxCarryJump(direction,1);} public static float weaponCarryMaxJumpAngle(Direction direction){return maxCarryJump(direction,2);} private static float maxCarryJump(Direction direction,int component){int row=atlasRow(direction);if(row<0)return Float.POSITIVE_INFINITY;float max=0f;for(int col=1;col<IDLE_WALK_COLUMNS;col++){float a=component==0?CARRY_FRAME_X[row][col-1]:component==1?CARRY_FRAME_Y[row][col-1]:CARRY_FRAME_ANGLE[row][col-1],b=component==0?CARRY_FRAME_X[row][col]:component==1?CARRY_FRAME_Y[row][col]:CARRY_FRAME_ANGLE[row][col];max=Math.max(max,Math.abs(b-a));}return max;}
  public static float actionHeightRatio(int source){if(source<0||source>=SOURCE_ACTION_COUNT)return 1f;return actionVisibleHeightPixels(source)/(float)SOURCE_FRAME_HEIGHT;} public static boolean legacyProceduralAttackReachable(){return false;} public static boolean hitCharacterPoseEnabled(){return false;} public static boolean weaponTransformUsesSingleMirror(){return true;} public static boolean attackFallbackWeaponSwingReachable(){return false;}
  private static final float[] ACTION_WEAPON_HAND_X={4.5f,13.5f,5.0f,15.0f},ACTION_WEAPON_HAND_Y={27.0f,27.0f,28.0f,27.0f}; public static float actionWeaponHandX(Direction d,CharacterSemanticRig.Anchors fallback){int i=actionSourceIndex(d);return i>=0&&i<ACTION_WEAPON_HAND_X.length?ACTION_WEAPON_HAND_X[i]:(fallback==null?0f:fallback.dominantHand.x);} public static float actionWeaponHandY(Direction d,CharacterSemanticRig.Anchors fallback){int i=actionSourceIndex(d);return i>=0&&i<ACTION_WEAPON_HAND_Y.length?ACTION_WEAPON_HAND_Y[i]:(fallback==null?0f:fallback.dominantHand.y);} public static float weaponAttackOffsetX(Direction direction){return 0f;} public static float weaponAttackOffsetY(Direction direction){return 0f;} public static float weaponAttackGripX(Direction direction){if(direction==null)return 0f;switch(direction){case NW:return -0.5f;case NE:return 0.5f;case SW:return -0.5f;case SE:return 0.5f;default:return 0f;}} public static float weaponAttackGripY(Direction direction){if(direction==null)return 0f;switch(direction){case NW:case NE:return 0.5f;case SW:case SE:return -0.5f;default:return 0f;}}
  /** Attack weapon has no independent temporal swing; orientation is fixed per BODY contact pose. */
  public static float weaponAttackAngle(Direction direction,float phase){if(direction==null)return 0f;switch(direction){case NW:return 32f;case SW:return 42f;case NE:return -32f;case SE:return -42f;default:return 0f;}}
  public static boolean weaponAttackUsesIndependentSwing(){return false;}
  private void drawRawSourceScaled(Canvas c,Bitmap bitmap,float left,float top,float scale){if(bitmap==null)return;c.drawBitmap(bitmap,null,new RectF(Math.round(left),Math.round(top),Math.round(left+bitmap.getWidth()*scale),Math.round(top+bitmap.getHeight()*scale)),pixelPaint);} private void drawRawSourceCroppedScaled(Canvas c,Bitmap bitmap,int srcLeft,int srcTop,int srcRight,int srcBottom,float left,float top,float scale){if(bitmap==null||srcRight<=srcLeft||srcBottom<=srcTop)return;Rect src=new Rect(srcLeft,srcTop,srcRight,srcBottom);RectF dst=new RectF(Math.round(left),Math.round(top),Math.round(left+(srcRight-srcLeft)*scale),Math.round(top+(srcBottom-srcTop)*scale));c.drawBitmap(bitmap,src,dst,pixelPaint);} private void drawAtlasCell(Canvas c,Bitmap atlas,int row,int col,int frameWidth,int frameHeight,float footAnchorX,float footAnchorY,float drawScale,float anchorY,float x){int left=col*frameWidth,top=row*frameHeight;Rect src=new Rect(left,top,left+frameWidth,top+frameHeight);float scaledWidth=frameWidth*drawScale,scaledHeight=frameHeight*drawScale,scaledAnchorX=footAnchorX*drawScale,scaledAnchorY=footAnchorY*drawScale;RectF dst=new RectF(Math.round(x-scaledAnchorX),Math.round(anchorY-scaledAnchorY),Math.round(x-scaledAnchorX+scaledWidth),Math.round(anchorY-scaledAnchorY+scaledHeight));c.drawBitmap(atlas,src,dst,pixelPaint);}
  private Bitmap tryLoadByName(Resources resources,String name,int expectedWidth,int expectedHeight){if(resources==null||name==null)return null;try{int resId=resources.getIdentifier(name,"drawable","com.projectdark.mobile");if(resId==0)return null;BitmapFactory.Options options=new BitmapFactory.Options();options.inScaled=false;Bitmap decoded=BitmapFactory.decodeResource(resources,resId,options);return validAtlas(decoded,expectedWidth,expectedHeight)?decoded:null;}catch(Throwable ignored){return null;}}
  public static int walkFrameIndex(float walkClock){float safeClock=Math.max(0f,walkClock),phase=safeClock%WALK_CYCLE_SECONDS;return Math.min(IDLE_WALK_COLUMNS-2,(int)Math.floor((phase+.00001f)/WALK_FRAME_SECONDS));} private Resources findProcessResources(){try{Class<?> activityThread=Class.forName("android.app.ActivityThread");Method currentApplication=activityThread.getDeclaredMethod("currentApplication");Object application=currentApplication.invoke(null);return application instanceof Context?((Context)application).getResources():null;}catch(Throwable ignored){return null;}} private static boolean validAtlas(Bitmap bitmap,int expectedWidth,int expectedHeight){return bitmap!=null&&bitmap.getWidth()==expectedWidth&&bitmap.getHeight()==expectedHeight;} /** BODY action02 source order is visually verified against the four extracted body frames: NW=0, NE=1, SW=2, SE=3. Weapon metadata is not a BODY source-map authority. */ public static int actionSourceIndex(Direction direction){return atlasRow(direction);} private static AnimationAction inferAnimationAction(State state,EffectFamily effect,String weaponVisualRef){if(state==State.ATTACK&&containsVisualRef(weaponVisualRef,CharacterVisualBinding.RESOLVED_WEAPON_APPEARANCE_ID))return AnimationAction.SWING;if(effect==EffectFamily.THROW)return AnimationAction.THROW;if(effect==EffectFamily.KICK)return AnimationAction.KICK;if(effect==EffectFamily.CAST||effect==EffectFamily.MAGIC)return AnimationAction.CAST;if(effect==EffectFamily.SKILL)return AnimationAction.SKILL;return state==State.ATTACK?AnimationAction.PUNCH:null;}
  private void drawSafePeasantFallback(Canvas c,Pose pose,float anchorY){boolean left=pose.direction==Direction.NW||pose.direction==Direction.SW,down=pose.direction==Direction.SW||pose.direction==Direction.SE;int frame=pose.state==State.WALK?walkFrameIndex(presentationWalkClock):0,step=frame==1?-1:frame==3?1:0;float phase=pose.stateDuration<=0f?0f:Math.max(0f,Math.min(1f,pose.stateClock/pose.stateDuration));c.save();c.translate(pose.x-12f*PLAYER_RENDER_SCALE,anchorY-32f*PLAYER_RENDER_SCALE);c.scale(PLAYER_RENDER_SCALE,PLAYER_RENDER_SCALE);int outline=0xff1d1917,skin=pose.hitFlash?0xffffd7ca:0xffc98d67,skinHi=0xffe4b087,hair=0xff4b3426,hairHi=0xff72513a,hairShadow=0xff2c201a,cloth=0xff8b7656,clothHi=0xffad956d,clothShadow=0xff64543f,pants=0xff4b4540,pantsHi=0xff635c55,shoe=0xff332c28;int nearX=left?7:14,farX=left?13:8;px(c,outline,9,19,7,4);px(c,pants,10,19,5,3);px(c,outline,farX+step,21,3,8);px(c,pants,farX+step+1,22,2,6);px(c,shoe,farX+step-1,28,5,3);px(c,outline,nearX-step,20,4,9);px(c,pantsHi,nearX-step+1,21,2,7);px(c,shoe,nearX-step-1,28,6,3);int torsoX=left?7:9;px(c,outline,torsoX,9,9,12);px(c,clothShadow,torsoX+1,10,7,10);px(c,cloth,torsoX+2,10,6,9);px(c,clothHi,torsoX+2,10,2,2);int farShoulder=left?15:8;px(c,outline,farShoulder,11,3,8);px(c,skin,farShoulder+(left?0:1),12,2,6);int nearShoulder=left?6:17;px(c,outline,nearShoulder,11,4,8);px(c,skin,nearShoulder+(left?0:1),12,3,6);int headX=left?8:7;px(c,outline,headX,1,10,9);px(c,hairShadow,headX,1,10,5);px(c,hair,headX+1,1,8,5);px(c,hairHi,headX+2,1,4,1);if(down){px(c,skin,headX+1,4,8,5);px(c,skinHi,headX+2,4,2,2);px(c,0xff281d19,left?headX+3:headX+6,6,1,1);}else px(c,skin,headX+2,5,6,4);if(pose.state==State.CAST||pose.state==State.SKILL){fxPaint.setStyle(Paint.Style.STROKE);fxPaint.setStrokeWidth(2f);fxPaint.setColor(0xcc79cfff);c.drawCircle(12+(left?-5f:5f),8,4+phase*5f,fxPaint);fxPaint.setStyle(Paint.Style.FILL);}if(pose.state==State.DEAD)c.rotate(left?-72f:72f,12f,30f);c.restore();}
  private void px(Canvas c,int color,float x,float y,float w,float h){pixelPaint.setStyle(Paint.Style.FILL);pixelPaint.setColor(color);c.drawRect(x,y,x+w,y+h,pixelPaint);} public boolean hasRequiredStateContract(){return CharacterRendererAudit.passes();} public String contractAuditSummary(){return CharacterRendererAudit.summary();} public boolean ownsPlayerLocalEffects(){return true;} public float playerRenderScale(){return PLAYER_RENDER_SCALE;} public boolean usesDefaultAtlasFor(State state){return state==State.IDLE||state==State.WALK||state==State.HIT?resourceAtlasActive():state==State.ATTACK&&sourceActionActive();}
}