package com.projectdark.mobile;
import java.util.*;
/** Combat presentation event projection; no drawing/HUD ownership. */
public final class CombatFeedbackStream {
 public enum Type{ACTION_STARTED,ACTION_REJECTED,ACTION_CANCELLED,EFFECT_APPLIED,HIT,CRIT,MISS,HEAL,MONSTER_DEFEATED} public interface AnchorPort{float anchorX(String id);float anchorY(String id);}
 public static final class Event{public final long sequence,resolverSequence,actionSequence;public final Type type;public final String actorId,targetId,actionId;public final CombatResolver.ActionState actionState;public final CombatResolver.EffectType effectType;public final CombatResolver.InputMode inputMode;public final CombatResolver.RejectReason rejectReason;public final int amount;Event(long s,CombatResolver.Event e,Type t){sequence=s;resolverSequence=e.sequence;actionSequence=e.actionSequence;type=t;actorId=e.actorId;targetId=e.targetId;actionId=e.actionId;actionState=e.state;effectType=e.effectType;inputMode=e.inputMode;rejectReason=e.rejectReason;amount=e.amount;}}
 private final Deque<Event> events=new ArrayDeque<>();private final DamageNumberModel nums=new DamageNumberModel();private long seq;public void consume(List<CombatResolver.Event> src,AnchorPort a){if(src==null)return;for(CombatResolver.Event e:src){Type t=map(e);if(t==null)continue;events.add(new Event(++seq,e,t));while(events.size()>128)events.removeFirst();if(e.type==CombatResolver.EventType.HIT_FEEDBACK&&a!=null)nums.spawn(e.targetId,sem(e.hitSemantic),e.amount,a.anchorX(e.targetId),a.anchorY(e.targetId));}}public void tick(float d){nums.tick(d);}public List<Event> drainEvents(){List<Event>o=new ArrayList<>(events);events.clear();return Collections.unmodifiableList(o);}public List<DamageNumberModel.Snapshot> damageNumbers(){return nums.snapshot();}
 private static Type map(CombatResolver.Event e){switch(e.type){case ACTION_STARTED:return Type.ACTION_STARTED;case ACTION_REJECTED:return Type.ACTION_REJECTED;case ACTION_CANCELLED:return Type.ACTION_CANCELLED;case EFFECT_APPLIED:return Type.EFFECT_APPLIED;case MONSTER_DEFEATED:return Type.MONSTER_DEFEATED;case HIT_FEEDBACK:switch(e.hitSemantic){case CRIT:return Type.CRIT;case MISS:return Type.MISS;case HEAL:return Type.HEAL;default:return Type.HIT;}default:return null;}}private static DamageNumberModel.SemanticType sem(CombatResolver.HitSemantic s){if(s==null)return DamageNumberModel.SemanticType.DAMAGE;switch(s){case CRIT:return DamageNumberModel.SemanticType.CRIT;case MISS:return DamageNumberModel.SemanticType.MISS;case HEAL:return DamageNumberModel.SemanticType.HEAL;default:return DamageNumberModel.SemanticType.DAMAGE;}}
}
