package com.projectdark.mobile;
import android.content.Context;
import android.content.SharedPreferences;
import java.util.Map;
/** Durable F5M + RPG restart boundary. */
public final class F5mSaveStore{
 private static final String PREF="project_dark_f5m_v1",K_STATE="quest_state",K_COUNT="quest_count",K_TOKEN="training_token_qty",K_REWARD_CLAIMED="quest_reward_claimed",K_LEVEL="normal_level",K_EXP="normal_exp",K_GOLD="gold",K_STR="str",K_INT="int",K_WIS="wis",K_CON="con",K_DEX="dex",K_SP="stat_points",K_EQUIP="equipment_ids",K_Q2_STATE="quest2_state",K_Q2_COUNT="quest2_count",K_BASE_HP="base_max_hp_v3",K_BASE_MP="base_max_mp_v3";
 private static F5mSaveStore active;private final SharedPreferences prefs;
 private F5mSaveStore(Context c){prefs=c.getApplicationContext().getSharedPreferences(PREF,Context.MODE_PRIVATE);}public static void install(Context c){active=new F5mSaveStore(c);}public static boolean installed(){return active!=null;}
 public static void restoreQuestActive(F5mAdaptedPrologueQuest q){if(active!=null)active.restoreQuest(q);}public static void saveQuestActive(F5mAdaptedPrologueQuest q){if(active!=null)active.saveQuest(q);}public static void restoreRewardsActive(RpgProgressionState r){if(active!=null)active.restoreRpg(r);}public static void saveRewardsActive(RpgProgressionState r){if(active!=null)active.saveRpg(r);}public static void restoreQuest2Active(GrowthQuest2 q){if(active!=null)active.restoreQuest2(q);}public static void saveQuest2Active(GrowthQuest2 q){if(active!=null)active.saveQuest2(q);}public static boolean rewardClaimedActive(){return active!=null&&active.prefs.getBoolean(K_REWARD_CLAIMED,false);}
 public static boolean commitTurnInActive(F5mAdaptedPrologueQuest q,RpgProgressionState r){if(active==null||q==null||r==null)return false;if(q.state()!=F5mAdaptedPrologueQuest.State.RETURN_READY)return q.state()==F5mAdaptedPrologueQuest.State.COMPLETED&&rewardClaimedActive();int qty=qty(r);if(qty<1)return false;boolean ok=active.prefs.edit().putBoolean(K_REWARD_CLAIMED,true).putInt(K_TOKEN,qty).putInt(K_LEVEL,r.normalLevel()==null?1:r.normalLevel()).putLong(K_EXP,r.normalExp()==null?0L:r.normalExp()).putLong(K_GOLD,r.gold()==null?0L:r.gold()).putString(K_STATE,F5mAdaptedPrologueQuest.State.COMPLETED.name()).putInt(K_COUNT,q.currentCount()).commit();if(ok)q.restore(F5mAdaptedPrologueQuest.State.COMPLETED,q.currentCount());return ok;}
 private void restoreQuest2(GrowthQuest2 q){String raw=prefs.getString(K_Q2_STATE,null);if(raw==null)return;try{q.restore(GrowthQuest2.State.valueOf(raw),prefs.getInt(K_Q2_COUNT,0));}catch(IllegalArgumentException ignored){q.restore(GrowthQuest2.State.LOCKED,0);}}
 private void saveQuest2(GrowthQuest2 q){prefs.edit().putString(K_Q2_STATE,q.state().name()).putInt(K_Q2_COUNT,q.currentCount()).apply();}
 private void restoreQuest(F5mAdaptedPrologueQuest q){String raw=prefs.getString(K_STATE,null);if(raw==null)return;try{q.restore(F5mAdaptedPrologueQuest.State.valueOf(raw),prefs.getInt(K_COUNT,0));}catch(IllegalArgumentException ignored){q.restore(F5mAdaptedPrologueQuest.State.AVAILABLE,0);}}
 private void saveQuest(F5mAdaptedPrologueQuest q){prefs.edit().putString(K_STATE,q.state().name()).putInt(K_COUNT,q.currentCount()).apply();}
 private void restoreRpg(RpgProgressionState r){int desired=Math.max(0,prefs.getInt(K_TOKEN,0)),current=qty(r);if(desired>current)r.autoLootResolvedItem(AdaptedPrototypeRewardCatalog.TRAINING_TOKEN_ITEM_ID,desired-current);ProgressionLeveling.restore(r,prefs.getInt(K_LEVEL,1),prefs.getLong(K_EXP,0L));r.restoreGold(prefs.getLong(K_GOLD,0L));r.restoreStats(prefs.getInt(K_STR,3),prefs.getInt(K_INT,3),prefs.getInt(K_WIS,3),prefs.getInt(K_CON,3),prefs.getInt(K_DEX,3),prefs.getInt(K_SP,0));r.restoreBaseResources(prefs.getInt(K_BASE_HP,r.baseMaxHp()),prefs.getInt(K_BASE_MP,r.baseMaxMp()));String raw=prefs.getString(K_EQUIP,"");if(!raw.isEmpty())for(String id:raw.split("\\|")){if(id.isEmpty())continue;RpgProgressionState.ItemDefinition d=r.itemDefinitions().get(id);if(d!=null&&!id.equals(r.equipment().get(d.equipSlot)))r.equip(id);}}
 private void saveRpg(RpgProgressionState r){StringBuilder eq=new StringBuilder();for(Map.Entry<String,String> e:r.equipment().entrySet()){if(eq.length()>0)eq.append('|');eq.append(e.getValue());}prefs.edit().putInt(K_TOKEN,qty(r)).putInt(K_LEVEL,r.normalLevel()==null?1:r.normalLevel()).putLong(K_EXP,r.normalExp()==null?0L:r.normalExp()).putLong(K_GOLD,r.gold()==null?0L:r.gold()).putInt(K_STR,r.str()).putInt(K_INT,r.intel()).putInt(K_WIS,r.wis()).putInt(K_CON,r.con()).putInt(K_DEX,r.dex()).putInt(K_SP,r.statPoints()).putInt(K_BASE_HP,r.baseMaxHp()).putInt(K_BASE_MP,r.baseMaxMp()).putString(K_EQUIP,eq.toString()).apply();}
 private static int qty(RpgProgressionState r){Integer q=r.inventory().get(AdaptedPrototypeRewardCatalog.TRAINING_TOKEN_ITEM_ID);return q==null?0:q;}
}