package com.projectdark.mobile;

/** Generated from the reviewed per-ID decisions; do not infer rules from skill names. */
final class SkillActionData {
  static final String[][] ROWS={
    {"SK_전사_001", "숏블레이드", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_전사_002", "더블어택", "LINKED", "FRONT", "1", "1", "PRESENTATION", "2", "0.14", "V", "독립 시전이 아닌 기본공격 연동 추가 타격", "기술"},
    {"SK_전사_003", "윈드블레이드", "ACTIVE", "FRONT", "3", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "같은 방향의 연속 세 타일", "기술"},
    {"SK_전사_004", "디바투", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_전사_005", "트리플어택", "LINKED", "FRONT", "1", "1", "PRESENTATION", "3", "0.14", "V", "독립 시전이 아닌 기본공격 연동 추가 타격", "기술"},
    {"SK_전사_006", "메가블레이드", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "시전자 사방 한 타일; 대각선 제외", "기술"},
    {"SK_전사_007", "바투", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "기술"},
    {"SK_전사_008", "투핸드어택", "PASSIVE", "PASSIVE", "0", "0", "PRESENTATION", "1", "0.14", "V", "양손무기 장착 허용 패시브: 공격 모션/피격 이펙트 없음", "기술"},
    {"SK_전사_009", "드래곤모드", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_전사_010", "피닉스모드", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_전사_011", "적무기쳐내기", "ACTIVE", "FRONT", "1", "1", "PRESENTATION", "1", "0.14", "ADAPTED_MELEE_REACH_ORIGINAL_UNRESOLVED", "근접 한 타일 임시 적용; 필살기 원작 최대 발동 거리는 추가 영상 확인 필요.", "기술"},
    {"SK_전사_012", "레스큐", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "기술"},
    {"SK_전사_013", "매드소울", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "ADAPTED_MELEE_REACH_ORIGINAL_UNRESOLVED", "근접 한 타일 임시 적용; 필살기 원작 최대 발동 거리는 추가 영상 확인 필요.; 원작 플레이 GIF의 실제 프레임/시간 추출, 가림/알파는 한계 명시. 캡처된 BODY는 렌더하지 않음.", "기술"},
    {"SK_전사_014", "완전방어", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상; 20260930 영상: 캐릭터를 감싸는 얇은 파란 구형 보호막, 적 피격 없음.", "기술"},
    {"SK_전사_015", "크래셔", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "ADAPTED_MELEE_REACH_ORIGINAL_UNRESOLVED", "근접 한 타일 임시 적용; 필살기 원작 최대 발동 거리는 추가 영상 확인 필요.; 사용자 확인: 크래셔/데빌크래셔 공통 형상, 파랑/빨강 구분. 기존 불꽃 기둥 폐기.; 원작 플레이 GIF의 실제 프레임/시간 추출, 가림/알파는 한계 명시. 캡처된 BODY는 렌더하지 않음.", "기술"},
    {"SK_전사_016", "스톰블레이드", "ACTIVE", "FRONT", "3", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "같은 방향의 연속 세 타일", "기술"},
    {"SK_전사_017", "룬블레이드", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "시전자 사방 한 타일; 대각선 제외", "기술"},
    {"SK_전사_018", "집중", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_전사_019", "포효", "ACTIVE", "SCREEN", "0", "0", "PRESENTATION", "1", "0.14", "V", "현재 화면 안의 적 전체; 화면 밖 제외", "기술"},
    {"SK_전사_020", "메가어택", "LINKED", "FRONT", "1", "1", "PRESENTATION", "4", "0.14", "V", "독립 시전이 아닌 기본공격 연동 추가 타격", "기술"},
    {"SK_전사_021", "돌진", "UTILITY", "FRONT", "5", "1", "PRESENTATION", "1", "0.14", "V_RANGE_TRAVEL_UNRESOLVED_RUNTIME", "원작 전방5칸 돌진 확인. 충돌/착지 규칙 확인 및 이동 서비스 구현 전에는 제자리 가짜 공격을 출력하지 않음.", "기술"},
    {"SK_전사_022", "매드소울진", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "ADAPTED_MELEE_REACH_ORIGINAL_UNRESOLVED", "근접 한 타일 임시 적용; 필살기 원작 최대 발동 거리는 추가 영상 확인 필요.; 원작 플레이 GIF의 실제 프레임/시간 추출, 가림/알파는 한계 명시. 캡처된 BODY는 렌더하지 않음.", "기술"},
    {"SK_전사_023", "데빌크래셔", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "ADAPTED_MELEE_REACH_ORIGINAL_UNRESOLVED", "근접 한 타일 임시 적용; 필살기 원작 최대 발동 거리는 추가 영상 확인 필요.; 사용자 확인: 크래셔/데빌크래셔 공통 형상, 파랑/빨강 구분. 기존 불꽃 기둥 폐기.; 원작 플레이 GIF의 실제 프레임/시간 추출, 가림/알파는 한계 명시. 캡처된 BODY는 렌더하지 않음.", "기술"},
    {"SK_도적_001", "찌르기", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_002", "센스몬스터", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "기술"},
    {"SK_도적_003", "표창날리기", "ACTIVE", "SINGLE", "4", "2", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V_MAX4_NONADJACENT_METRIC_ADAPTED", "최대4칸, 붙어서 사용 불가. 타일 거리 측정 방식은 프로젝트 Chebyshev 기준.", "기술"},
    {"SK_도적_004", "밀기", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "기술"},
    {"SK_도적_005", "아무네지아", "ACTIVE", "SINGLE", "4", "2", "PRESENTATION", "1", "0.14", "V_NONADJACENT_MAX_UNRESOLVED_ADAPTED4", "인접 대상 사용 불가: 최소 두 타일 거리. 최대4칸은 프로젝트 임시 상한.", "기술"},
    {"SK_도적_006", "연막탄터뜨리기", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "기술"},
    {"SK_도적_007", "찔러휘비기", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_008", "더블어택", "LINKED", "FRONT", "1", "1", "PRESENTATION", "2", "0.14", "V", "독립 시전이 아닌 기본공격 연동 추가 타격", "기술"},
    {"SK_도적_009", "품뒤져보기", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_010", "센스", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_011", "하이드", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_도적_012", "함정찾기1", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_013", "라이트닝무브", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_도적_014", "두번찌르기", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_015", "습격", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_016", "센서스", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_017", "함정찾기2", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_018", "함정해체", "UTILITY", "UTILITY", "1", "1", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_019", "적갑옷해체", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "기술"},
    {"SK_도적_020", "암살격", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일; 원작 플레이 GIF의 실제 프레임/시간 추출, 가림/알파는 한계 명시. 캡처된 BODY는 렌더하지 않음.", "기술"},
    {"SK_도적_021", "마구찌르기", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_022", "슬래쉬", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_023", "기습", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_024", "트리플어택", "LINKED", "FRONT", "1", "1", "PRESENTATION", "3", "0.14", "V", "독립 시전이 아닌 기본공격 연동 추가 타격", "기술"},
    {"SK_도적_025", "함정파기", "UTILITY", "UTILITY", "1", "1", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_026", "하이더", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_도적_027", "암살격진", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일; 원작 플레이 GIF의 실제 프레임/시간 추출, 가림/알파는 한계 명시. 캡처된 BODY는 렌더하지 않음.", "기술"},
    {"SK_도적_028", "습격진", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_029", "백스탭", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_도적_030", "백슬래쉬", "ACTIVE", "FRONT_BACK", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "시전자 전후 한 타일; 옆 제외", "기술"},
    {"SK_도적_031", "설치형트랩", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_마법사_001", "마레노", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_002", "렌토", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_003", "테라미코", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_004", "아듀로", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_005", "플라모", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_006", "콘푸지오", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_007", "수페라마레나", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "시전자 사방 한 타일; 대각선 제외", "마법"},
    {"SK_마법사_008", "수페라테라미카", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "시전자 사방 한 타일; 대각선 제외", "마법"},
    {"SK_마법사_009", "수페라아듀라", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "시전자 사방 한 타일; 대각선 제외", "마법"},
    {"SK_마법사_010", "수페라플라미카", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "시전자 사방 한 타일; 대각선 제외", "마법"},
    {"SK_마법사_011", "바르도", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_012", "베노미", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_013", "마레누스", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_014", "테라미쿠스", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_015", "아듀로스", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_016", "플라무스", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_017", "나르콜리", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_018", "엑스마레나", "ACTIVE", "TARGET_CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "선택 대상과 그 사방 한 타일", "마법"},
    {"SK_마법사_019", "엑스테라미카", "ACTIVE", "TARGET_CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "선택 대상과 그 사방 한 타일", "마법"},
    {"SK_마법사_020", "엑스아듀라", "ACTIVE", "TARGET_CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "선택 대상과 그 사방 한 타일", "마법"},
    {"SK_마법사_021", "엑스플라미카", "ACTIVE", "TARGET_CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "선택 대상과 그 사방 한 타일", "마법"},
    {"SK_마법사_022", "로카테오", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "마법"},
    {"SK_마법사_023", "딜루메니", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_024", "데프레코", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_025", "소루마", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_026", "마레네라", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_027", "테라미에라", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_028", "아듀레나", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_029", "플라메라", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_030", "마네나로", "ACTIVE", "SCREEN", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "현재 화면 안의 적 전체; 화면 밖 제외", "마법"},
    {"SK_마법사_031", "테라미칼로", "ACTIVE", "SCREEN", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "현재 화면 안의 적 전체; 화면 밖 제외", "마법"},
    {"SK_마법사_032", "아듀랄로", "ACTIVE", "SCREEN", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "현재 화면 안의 적 전체; 화면 밖 제외", "마법"},
    {"SK_마법사_033", "플라미칼로", "ACTIVE", "SCREEN", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "현재 화면 안의 적 전체; 화면 밖 제외", "마법"},
    {"SK_마법사_034", "세멜리아", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_035", "아마게돈", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_RADIUS_ADAPTED1", "암흑 사방 공격; 반경 한 타일 프로젝트 적용.", "마법"},
    {"SK_마법사_036", "숨마스텔라", "ACTIVE", "TARGET_CROSS", "4", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "대상 중심 사방4칸. 대각선 제외.", "마법"},
    {"SK_마법사_037", "라그나로크", "ACTIVE", "SCREEN", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "현재 화면 안의 적 전체; 화면 밖 제외", "마법"},
    {"SK_마법사_038", "데스", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_039", "아이스블러스트", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_040", "퀘이크", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_041", "플레쉬스톰", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_042", "플레어", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_043", "메테오", "ACTIVE", "SCREEN", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "현재 화면 안의 적 전체; 화면 밖 제외", "마법"},
    {"SK_마법사_044", "속성강화", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V", "자기 대상", "마법"},
    {"SK_마법사_045", "매직프로텍션", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V", "자기 대상", "마법"},
    {"SK_마법사_046", "어둠의각인", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_마법사_047", "렌티아", "ACTIVE", "SCREEN", "0", "0", "PRESENTATION", "1", "0.24", "V_PDF_CORRECTED_MASTER", "렌티아·바르데아·데프레타·프라베라는 화면 전체 저주. 기존 Master 단일 표기는 정정 제안으로 보존.", "마법"},
    {"SK_마법사_048", "바르데아", "ACTIVE", "SCREEN", "0", "0", "PRESENTATION", "1", "0.24", "V_PDF_CORRECTED_MASTER", "렌티아·바르데아·데프레타·프라베라는 화면 전체 저주. 기존 Master 단일 표기는 정정 제안으로 보존.", "마법"},
    {"SK_마법사_049", "데프레타", "ACTIVE", "SCREEN", "0", "0", "PRESENTATION", "1", "0.24", "V_PDF_CORRECTED_MASTER", "렌티아·바르데아·데프레타·프라베라는 화면 전체 저주. 기존 Master 단일 표기는 정정 제안으로 보존.", "마법"},
    {"SK_마법사_050", "프라베라", "ACTIVE", "SCREEN", "0", "0", "PRESENTATION", "1", "0.24", "V_PDF_CORRECTED_MASTER", "렌티아·바르데아·데프레타·프라베라는 화면 전체 저주. 기존 Master 단일 표기는 정정 제안으로 보존.", "마법"},
    {"SK_마법사_051", "델리스펠라스", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V", "자기 대상", "마법"},
    {"SK_마법사_052", "포트리스", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V", "자기 대상", "마법"},
    {"SK_성직자_001", "쿠로", "ACTIVE", "ALLY", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "체력 회복 1단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_002", "수혈", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "아군 단일; 현재 런타임에서는 자신만 선택 가능", "마법"},
    {"SK_성직자_003", "디렌토", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "저주 1단계 렌토 마법 해제 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_004", "벨라르모", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "초급축복마법 - 집중력을 높힌다. (HIT+10) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_005", "쿠라노", "ACTIVE", "ALLY", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "체력회복 2단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_006", "디바르도", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "저주 2단계 바르도 마법해제 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_007", "쿠러스", "ACTIVE", "GROUP", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "그룹 체력회복 1단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_008", "디베노모", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "중독 해제 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_009", "에나르마", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "초급 축복 마법 - 공격력 상승 (DMG+2) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_011", "쿠라노소", "ACTIVE", "ALLY", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "체력 회복 3단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_012", "바르도", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_성직자_013", "홀리볼트", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "성스러운 번개로 공격하는 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_014", "디데프레카", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "저주 3단계 데프레코 마법 해제 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_015", "쿠라누스", "ACTIVE", "GROUP", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V", "그룹 체력 회복 2단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_016", "쿠랄툼", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V", "자기재생력 향상 (재생력+20) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_017", "실드", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "자신의 사방에 보호막 설치 (몬스터접근x) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음. 사방 통행 차단의 실제 도메인 서비스는 미구현.", "마법"},
    {"SK_성직자_018", "콜라마", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "중급마법 - 갑옷을 단단하게 한다 (AC-10) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_019", "수페라벨라르모", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "중급마법 - 집중력을 더욱 높게한다. (HIT+20) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_020", "홀리블로우", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_성직자_021", "수페라쿠라노", "ACTIVE", "ALLY", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "체력 회복 4단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_022", "로카메아", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "그룹원을 자신의 앞으로 소환한다.조건 1. 같은 국적 및 마을서버조건 2. 자신의 캐릭터보다 낮은 서열(하단 이미지 참고) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_023", "디프라바", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "저주 4단계 프라보 마법 해제 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_024", "리치마나", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "그룹원의 마나를 빼앗는다(회복). · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_025", "소모니아", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "하급 몬스터 소환마법조건 1. 무속성의 몬스터조건 2. 몬스터 Lv. 98 이하의 몬스터조건 3. 마법을 쓰지 않는 몬스터 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_026", "디소루마", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "소루마 해제 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_027", "쿠라네라", "ACTIVE", "GROUP", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V", "그룹 체력회복 3단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_028", "호르라마", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "상급축복마법 - 보호마법 (타격 50%감소) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_029", "이모탈", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "무적 토글 마법(기술,마법 공격 보호) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_030", "코마디아", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "코마상태 해제 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_031", "리베라토", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "모든 상태이상 마법 해제 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_032", "엑스쿠라노", "ACTIVE", "ALLY", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "체력회복 5단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_033", "엑스쿠라네라", "ACTIVE", "GROUP", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V", "그룹 체력회복 4단계 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_034", "리플렉토", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "마법공격 반사 토글 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_035", "수페라에나르마", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "아군 단일; 현재 런타임에서는 자신만 선택 가능", "마법"},
    {"SK_성직자_036", "엑스벨라룸", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "아군 단일; 현재 런타임에서는 자신만 선택 가능", "마법"},
    {"SK_성직자_037", "칸의축복", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "아군 단일; 현재 런타임에서는 자신만 선택 가능", "마법"},
    {"SK_성직자_038", "신의축복", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_039", "홀리큐어", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "아군 단일; 현재 런타임에서는 자신만 선택 가능", "마법"},
    {"SK_성직자_040", "홀리드래곤", "ACTIVE", "SCREEN", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V", "화면 전체, 이름과 달리 암흑 속성(2005 실험 및 PDF). 용 이펙트 원본은 미확보.", "마법"},
    {"SK_성직자_041", "디렌타", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_042", "디바르데아", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_043", "디데프레타", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_044", "디프라베라", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_045", "홀리큐레스", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_046", "일루메룸", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_047", "디나르콜룸", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_048", "디베노메라", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_성직자_049", "디소루메라", "ACTIVE", "GROUP", "0", "0", "PRESENTATION", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_무도가_001", "정권", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_무도가_002", "단각", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "﻿전방대상 앞차기 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_003", "이형환위", "UTILITY", "FRONT", "3", "1", "PRESENTATION", "1", "0.14", "V_TRAVEL_UNRESOLVED_RUNTIME", "전방 3칸 대상을 뛰어넘는다. · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음. 이동/착지 서비스 미구현: 시전 차단.", "기술"},
    {"SK_무도가_004", "미종보법", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "몸을 가볍게하여 공격을 피한다. · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_무도가_005", "양의신권", "LINKED", "FRONT", "1", "1", "PRESENTATION", "2", "0.14", "V", "(일반 기본 공격 모션)기본 공격 시 2회 타격 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_006", "통배권", "ACTIVE", "FRONT", "1", "1", "PRESENTATION", "1", "0.14", "V", "몬스터를 독에 걸리게 한다. · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_007", "붕각", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 대상 돌려차기 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_008", "경신공", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "이동속도를 높힌다. (Speed+1) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_무도가_009", "백보신권", "ACTIVE", "FRONT", "3", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 1~3칸 적 공격 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_010", "일음지", "ACTIVE", "FRONT", "1", "1", "PRESENTATION", "1", "0.14", "V", "몬스터의 이동을 제한시킨다 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_011", "흡정신공", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "몬스터의 체력을 흡수한다. · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_무도가_012", "쿠랄툼", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 재생력 향상 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_013", "철포삼", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "방어력 상승 마법 (AC-10) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_무도가_014", "선풍각", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "자기 주변 사방 돌려차기 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_015", "장풍", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "내공으로 적 원거리 공격 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_016", "금강불괴", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "무적상태 (토글마법) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_무도가_017", "쿠라노토", "ACTIVE", "SELF", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.14", "V", "자기 체력 회복 2단계 (HP + 500) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_018", "발경", "ACTIVE", "FRONT", "1", "1", "PRESENTATION", "1", "0.14", "V", "몬스터 대상을 얼린다. · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_019", "소수신공", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "기본공격 관련 기술 데미지 상승ex) 백보신권 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_020", "다라밀공", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "3.0", "V_RANGED_SINGLE_MAX_UNRESOLVED", "내공을 모두 모아 쏘는 필살기데미지 : (체력+마력-1440)*2 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음. INT53 정정 적용.", "마법"},
    {"SK_무도가_021", "구양신공", "ACTIVE", "CROSS", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V_SHAPE_RADIUS_ADAPTED1", "사방의 적을 대상으로 하는 체력 소모 필살기 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_022", "반탄신공", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "기술반사 (토글마법) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_무도가_023", "달마신공", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V_FRONT_MAX_UNRESOLVED_ADAPTED1", "전방의 적을 대상으로 하는 체력 소모 필살기(체력 30%를 상대방에게 데미지로 전달)- 이모탈, 버프등 영향 받지 않는 스킬 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "기술"},
    {"SK_무도가_024", "연천단각", "ACTIVE", "FRONT", "1", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "전방 인접 한 타일", "기술"},
    {"SK_무도가_025", "붕신선각", "ACTIVE", "AROUND", "1", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "시전자 둘레 여덟 타일; 자신 제외", "기술"},
    {"SK_무도가_026", "파천각", "ACTIVE", "UNRESOLVED", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED", "원작 대상/범위 미확정: 잘못된 타격과 이펙트를 출력하지 않음", "기술"},
    {"SK_무도가_027", "트리플펀치", "LINKED", "FRONT", "1", "1", "PRESENTATION", "3", "0.14", "V", "독립 시전이 아닌 기본공격 연동 추가 타격", "기술"},
    {"SK_무도가_028", "무영신공", "ACTIVE", "FRONT", "3", "1", "DAMAGE_ADAPTED_BALANCE", "1", "0.14", "V", "같은 방향의 연속 세 타일", "기술"},
    {"SK_무도가_029", "자기보호", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "자기 대상", "기술"},
    {"SK_공통_001", "기본공격", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.14", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "기술"},
    {"SK_공통_002", "문열기", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_003", "탐색", "UTILITY", "UTILITY", "1", "1", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_004", "아들레스투", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "마법"},
    {"SK_공통_005", "휴식", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_006", "수영", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_007", "노점개설", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_008", "채집", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_009", "낚시", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_010", "쿠로토", "ACTIVE", "SELF", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V", "자기 대상", "마법"},
    {"SK_공통_011", "일반제조", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_012", "아이템고치기", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_공통_013", "마나스페라", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "마법"},
    {"SK_도적_032", "자물쇠열기", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_성직자_050", "아지토", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "마법"},
    {"SK_성직자_051", "블레스", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_성직자_052", "홀리쇼크", "ACTIVE", "SINGLE", "0", "0", "DAMAGE_ADAPTED_BALANCE", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_성직자_053", "디나르콜리", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "나르콜리 해제 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_054", "일루메나", "ACTIVE", "ALLY", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "딜루메니or연막(눈뽕) 시력회복 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_055", "디내추라", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "몬스터의 속성을 바꾸는 마법 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_056", "홀리쿠라노", "ACTIVE", "ALLY", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "아군 단일; 현재 런타임에서는 자신만 선택 가능", "마법"},
    {"SK_성직자_057", "홀리쿠라네라", "ACTIVE", "GROUP", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V", "그룹원 전체; 현재 런타임에 다른 아군 개체가 없어 자신만 포함", "마법"},
    {"SK_마법사_053", "프라보", "ACTIVE", "SINGLE", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "단일 원거리 발동 상한 미확정: 현재 화면 안 대상만 허용하는 프로젝트 규칙.", "마법"},
    {"SK_무도가_030", "일루메나", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "시력 회복 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_무도가_031", "디베노모", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.24", "V_CATALOG_SHAPE_REACH_UNRESOLVED", "중독 회복 · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_마법사_054", "클리멘스", "ACTIVE", "UNRESOLVED", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED", "이름만 확인. 효과와 범위 미확정이라 회복/공격으로 오인시키지 않음.", "마법"},
    {"SK_공통_014", "유즈스태프", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_033", "상자트랩해체", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_도적_034", "소매치기", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "기술"},
    {"SK_무도가_032", "쿠로토", "ACTIVE", "SELF", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V", "자기 체력 회복 마법 1단계 (HP+100) · 2020 세오서버 팬 자료; 현재 서버 수치와 동일하다고 판정하지 않음.", "마법"},
    {"SK_성직자_058", "쿠로토", "ACTIVE", "ALLY", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V_SHAPE_REACH_UNRESOLVED", "아군 단일; 현재 런타임에서는 자신만 선택 가능", "마법"},
    {"SK_성직자_059", "클리멘스", "ACTIVE", "UNRESOLVED", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "이름만 확인. 효과와 범위 미확정이라 회복/공격으로 오인시키지 않음.", "마법"},
    {"SK_성직자_060", "디노센스", "ACTIVE", "UNRESOLVED", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "이름만 확인. 효과와 범위 미확정이라 회복/공격으로 오인시키지 않음.", "마법"},
    {"SK_마법사_055", "아지토", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "마법"},
    {"SK_마법사_056", "쿠로토", "ACTIVE", "SELF", "0", "0", "HEAL_ADAPTED_BALANCE", "1", "0.24", "V", "자기 대상", "마법"},
    {"SK_마법사_057", "헬푸라", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.24", "UNRESOLVED_RUNTIME", "전투 공격 아님; 대상 서비스 미구현 상태에서 몬스터에게 가짜 피격 출력 금지", "마법"},
    {"SK_무도가_033", "경신공법", "ACTIVE", "SELF", "0", "0", "PRESENTATION", "1", "0.14", "V", "이동속도를 높힌다. (Speed+20%) · 이동속도/목적지 원작 서비스는 미구현.", "마법"},
    {"SK_무도가_034", "아지토", "UTILITY", "UTILITY", "0", "0", "PRESENTATION", "1", "0.14", "V", "소속된 국적의여관으로 순간이동 · 이동속도/목적지 원작 서비스는 미구현.", "마법"},
  };
}
