package com.projectdark.mobile;
import java.util.*;
/** Generated by tools/generate_equipment_stats.py; source/era receipts in Master. */
final class SourceEquipmentStats {
 private SourceEquipmentStats(){}
 static Map<String,Integer> forItem(String id){
  Map<String,Integer> m=new LinkedHashMap<>();
  switch(id){
   case "IT_TEST_WEAPON_MW002":
    m.put("MinATK",20);
    m.put("MaxATK",30);
    m.put("HIT",3);
    m.put("DAM",3);
    return m;
   case "IT_WEAPON_CHUNGRYONG":
    m.put("MinATK",1);
    m.put("MaxATK",2);
    return m;
   case "IT_REFERENCE_LEOPARD":
    m.put("AC",-79);
    m.put("HP",1500);
    m.put("MP",-500);
    m.put("STR",1);
    m.put("INT",-1);
    m.put("WIS",2);
    m.put("CON",-4);
    m.put("DEX",-2);
    m.put("MAGIC_DEFENSE",3);
    return m;
   case "IT_REFERENCE_HELM":
    m.put("AC",-12);
    m.put("HP",400);
    m.put("MP",500);
    m.put("MAGIC_DEFENSE",1);
    return m;
   case "IT_TEST_ARMOR_MU0000002":
    m.put("AC",-11);
    return m;
   case "IT_SHOP_ARMOR_JIPON":
    m.put("AC",-17);
    return m;
   case "IT_RING_THREELINEGOLD":
    m.put("AC",-1);
    m.put("HP",300);
    m.put("MP",150);
    m.put("MAGIC_DEFENSE",1);
    return m;
   case "IT_RING_REDJADE":
    m.put("HP",100);
    m.put("MP",50);
    return m;
   case "IT_RING_GORU":
    m.put("MP",150);
    return m;
   case "IT_RING_SILVERAQUA":
    m.put("AC",-1);
    m.put("DAM",1);
    m.put("HP",350);
    m.put("MP",170);
    m.put("STR",1);
    return m;
   default:return null;
  }
 }
}
