package com.projectdark.mobile;
import java.util.*;
/** Generated reviewed performance receipts; adapted fields are explicitly labelled. */
final class SourceEquipmentPerformance {
 static void install(RpgProgressionState r){
  r.installEquipmentPerformance("IT_SHOP_WEAPON_MW004",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_SHOP_WEAPON_MW005",stats("MinATK",33,"MaxATK",43,"LMinATK",3,"LMaxATK",4),26,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_ADAPTED_PLAYTEST_MOKDO",stats("MinATK",4,"MaxATK",14,"LMinATK",1,"LMaxATK",2),1,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_TEST_WEAPON_MW002",stats("MinATK",20,"MaxATK",30,"LMinATK",1,"LMaxATK",2),1,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_TEST_WEAPON_MW003",stats("MinATK",18,"MaxATK",28,"LMinATK",1,"LMaxATK",2),11,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WEAPON_CHUNGRYONG",stats("MinATK",1,"MaxATK",2,"LMinATK",1,"LMaxATK",2),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_JOB_WARRIOR_WEAPON",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_JOB_ROGUE_WEAPON",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_JOB_MAGE_WAND",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_JOB_CLERIC_WAND",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_WARRIOR_11",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_WARRIOR_26",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_ROGUE_11",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_ROGUE_26",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_MAGE_11",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_MAGE_26",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_CLERIC_11",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_B_CAMPAIGN_TOOL_CLERIC_26",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW007",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW009",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW010",stats("MinATK",31,"MaxATK",41,"LMinATK",3,"LMaxATK",4),26,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW011",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW012",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW013",stats("MinATK",34,"MaxATK",54,"LMinATK",4,"LMaxATK",6),41,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW014",stats("MinATK",40,"MaxATK",60,"LMinATK",3,"LMaxATK",5),41,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW016",stats("MinATK",140,"MaxATK",180,"LMinATK",12,"LMaxATK",16),71,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW017",stats("MinATK",49,"MaxATK",69,"LMinATK",5,"LMaxATK",7),56,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW018",stats("MinATK",124,"MaxATK",164,"LMinATK",14,"LMaxATK",18),71,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW019",stats("MinATK",180,"MaxATK",240),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW020",stats("MinATK",385,"MaxATK",425,"LMinATK",10,"LMaxATK",13),11,RpgProgressionState.Evidence.V);
  r.installEquipmentPerformance("IT_WARDROBE_MW021",stats("MinATK",134,"MaxATK",194,"LMinATK",15,"LMaxATK",21),86,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW022",stats("MinATK",160,"MaxATK",220),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW023",stats("MinATK",150,"MaxATK",210),86,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW026",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW027",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW029",stats("MinATK",20,"MaxATK",80),26,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW034",stats("MinATK",90,"MaxATK",110),56,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW035",stats("MinATK",40,"MaxATK",60),71,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW036",stats("MinATK",90,"MaxATK",110),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW037",stats("MinATK",180,"MaxATK",220),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW039",stats("MinATK",35,"MaxATK",45),41,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW040",stats("MinATK",60,"MaxATK",80),56,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW041",stats("MinATK",80,"MaxATK",110),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW043",stats("MinATK",80,"MaxATK",110),71,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW044",stats("MinATK",170,"MaxATK",190),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW047",stats("MinATK",80,"MaxATK",110,"LMinATK",9,"LMaxATK",12),86,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW048",stats("MinATK",190,"MaxATK",220,"LMinATK",18,"LMaxATK",21),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW049",stats("MinATK",90,"MaxATK",110),11,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW050",stats("MinATK",90,"MaxATK",100),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW051",stats("MinATK",90,"MaxATK",100),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW053",stats("MinATK",95,"MaxATK",120),11,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW055",stats("MinATK",234,"MaxATK",284),99,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW056",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.installEquipmentPerformance("IT_WARDROBE_MW059",stats("MinATK",4,"MaxATK",20,"LMinATK",6,"LMaxATK",30),11,RpgProgressionState.Evidence.FAN);
  r.installEquipmentPerformance("IT_WARDROBE_MW060",stats("MinATK",4,"MaxATK",20,"LMinATK",6,"LMaxATK",30,"MP",150),41,RpgProgressionState.Evidence.V);
  r.installEquipmentPerformance("IT_WARDROBE_MW062",stats("MinATK",8,"MaxATK",8),null,RpgProgressionState.Evidence.ADAPTED);
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_WOOD","나무방패",RpgProgressionState.SHIELD_SLOT,null,1,Collections.<String>emptySet(),false,null,null,stats("AC",-3,"MAGIC_DEFENSE",0),RpgProgressionState.Evidence.FAN));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_LEATHER","가죽방패",RpgProgressionState.SHIELD_SLOT,null,11,Collections.<String>emptySet(),false,null,null,stats("AC",-5,"MAGIC_DEFENSE",0),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_COPPER","구리방패",RpgProgressionState.SHIELD_SLOT,null,26,Collections.<String>emptySet(),false,null,null,stats("AC",-8,"MAGIC_DEFENSE",0),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_IRON","철방패",RpgProgressionState.SHIELD_SLOT,null,41,Collections.<String>emptySet(),false,null,null,stats("AC",-10,"MAGIC_DEFENSE",10),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_EXORCISM","퇴마방패",RpgProgressionState.SHIELD_SLOT,null,41,Collections.<String>emptySet(),false,null,null,stats("AC",-18,"MAGIC_DEFENSE",20),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_SKULL","해골방패",RpgProgressionState.SHIELD_SLOT,null,41,Collections.<String>emptySet(),false,null,null,stats("AC",-18,"MAGIC_DEFENSE",20),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_SILVER","은제방패",RpgProgressionState.SHIELD_SLOT,null,56,Collections.<String>emptySet(),false,null,null,stats("AC",-13,"MAGIC_DEFENSE",10),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_GOLD","금제방패",RpgProgressionState.SHIELD_SLOT,null,71,Collections.<String>emptySet(),false,null,null,stats("AC",-15,"MAGIC_DEFENSE",20),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_PAPAYA","파파야방패",RpgProgressionState.SHIELD_SLOT,null,71,Collections.<String>emptySet(),false,null,null,stats("AC",-20,"MAGIC_DEFENSE",30),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_PLANUM","플라늄방패",RpgProgressionState.SHIELD_SLOT,null,86,Collections.<String>emptySet(),false,null,null,stats("AC",-18,"MAGIC_DEFENSE",30),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_KNIGHT","기사단방패",RpgProgressionState.SHIELD_SLOT,null,99,Collections.<String>emptySet(),false,null,null,stats("AC",-20,"MAGIC_DEFENSE",30),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_PHOBOS","포보스의방패",RpgProgressionState.SHIELD_SLOT,null,null,Collections.<String>emptySet(),false,null,null,stats("AC",-22,"MAGIC_DEFENSE",30,"HIT",1,"DAM",2),RpgProgressionState.Evidence.V));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_BROKEN_PHOBOS","깨진포보스의방패",RpgProgressionState.SHIELD_SLOT,null,null,Collections.<String>emptySet(),false,null,null,stats("AC",-11,"MAGIC_DEFENSE",30),RpgProgressionState.Evidence.FAN));
  r.registerSourceAccessory(new RpgProgressionState.ItemDefinition("IT_SHIELD_DEATHKNIGHT","데스나이트의방패",RpgProgressionState.SHIELD_SLOT,null,null,Collections.<String>emptySet(),false,null,null,stats("AC",-25,"MAGIC_DEFENSE",30,"HP",-500,"MP",-500,"HIT",3,"DAM",3,"STR",1,"INT",1,"WIS",1,"CON",1,"DEX",1),RpgProgressionState.Evidence.V));
 }
 static String note(String id){switch(id){
 case "IT_SHOP_WEAPON_MW004":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_SHOP_WEAPON_MW005":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_ADAPTED_PLAYTEST_MOKDO":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_TEST_WEAPON_MW002":return "2008년 패치 후 에페 S20~30 / L1~2";
 case "IT_TEST_WEAPON_MW003":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WEAPON_CHUNGRYONG":return "확인된 청룡의숨결 공격력 S/L 1~2";
 case "IT_B_JOB_WARRIOR_WEAPON":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_JOB_ROGUE_WEAPON":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_JOB_MAGE_WAND":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_JOB_CLERIC_WAND":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_WARRIOR_11":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_WARRIOR_26":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_ROGUE_11":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_ROGUE_26":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_MAGE_11":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_MAGE_26":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_CLERIC_11":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_B_CAMPAIGN_TOOL_CLERIC_26":return "수련 장비 시험 공격력 8~8 · 추가 DAM/능력치 별도 적용";
 case "IT_WARDROBE_MW007":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_WARDROBE_MW009":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_WARDROBE_MW010":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW011":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_WARDROBE_MW012":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_WARDROBE_MW013":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW014":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW016":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW017":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW018":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW019":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW020":return "2006년 자료 S385~425 / L10~13";
 case "IT_WARDROBE_MW021":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW022":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW023":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW026":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_WARDROBE_MW027":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_WARDROBE_MW029":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW034":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW035":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW036":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW037":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW039":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW040":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW041":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW043":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW044":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW047":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW048":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW049":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW050":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW051":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW053":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW055":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW056":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_WARDROBE_MW059":return "과거 한국 서버 팬 자료의 공격력 · 현재 서버 확정치 아님";
 case "IT_WARDROBE_MW060":return "2019년 자료: 아리펠스탭 S4~20 / L6~30 · MP +150";
 case "IT_WARDROBE_MW062":return "원작 공격력 미확정 · 현재 시험 공격력 8~8 적용 (기존 기본값)";
 case "IT_SHIELD_WOOD":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인 · AC -3은 팬 표 기준 (2005년 -1 자료와 차이)";
 case "IT_SHIELD_LEATHER":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_COPPER":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_IRON":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_EXORCISM":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_SKULL":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_SILVER":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_GOLD":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_PAPAYA":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_PLANUM":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인 · 마법방어 30%는 넥슨 게시판 기준 (팬 표 20%와 차이)";
 case "IT_SHIELD_KNIGHT":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_PHOBOS":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_BROKEN_PHOBOS":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 case "IT_SHIELD_DEATHKNIGHT":return "장착 시 AC·마법방어 적용 · 착용 캐릭터 방패 외형 ID 미확인";
 default:return "";}}
 private static Map<String,Integer> stats(Object... kv){Map<String,Integer> m=new LinkedHashMap<>();for(int i=0;i<kv.length;i+=2)m.put((String)kv[i],(Integer)kv[i+1]);return m;}
}
