package com.projectdark.mobile;
import android.content.Context;import android.graphics.*;import com.projectdark.mobile.world.TownInteriorDef;import java.util.*;
/** Reference-inspired wood list/details/dialogue UI; confirmation contains the exact durable operation. */
public final class TownShopWindow {
 private final Paint p=new Paint();private final java.text.DecimalFormat amounts=new java.text.DecimalFormat("#,##0");private final SourceItemIconRegistry sourceIcons;private final ReagentItemVisualRegistry reagent;private final EquipmentVisualRegistry gear;private final Bitmap portraits;private final Map<String,Bitmap> iconCache=new HashMap<>();
 private final Context context;private int session;private boolean open,confirm;private int tab,page,selected,quantity=1;private String filter="전체",notice="원하는 상품을 선택해 주세요.";
 private String campaignNpc;private TownInteriorDef def;private RuntimeState state;
 public TownShopWindow(Context c){context=c;sourceIcons=new SourceItemIconRegistry(c);reagent=new ReagentItemVisualRegistry(c);gear=new EquipmentVisualRegistry(c);Bitmap b=null;try(java.io.InputStream in=c.getAssets().open("interiors/v85/portraits.webp")){b=BitmapFactory.decodeStream(in);}catch(java.io.IOException e){}portraits=b;p.setAntiAlias(true);}
 public boolean isOpen(){return open;}public void close(){session++;open=false;confirm=false;}public void open(TownInteriorDef d,RuntimeState s){session++;def=d;state=s;open=true;campaignNpc=null;confirm=false;tab=page=selected=0;quantity=1;filter="전체";notice=d.kind==TownInteriorDef.Kind.BANK?"골드와 물품을 안전하게 보관해 드립니다.":d.kind==TownInteriorDef.Kind.CHURCH?"평안이 함께하시기를. 회복에는 50 Gold가 필요합니다.":"상품을 선택하고 수량과 금액을 확인해 주세요.";}
 public void openCampaign(RuntimeState s){for(TownInteriorDef d:TownInteriorDef.ALL)if(d.kind==TownInteriorDef.Kind.EQUIPMENT){open(d,s);campaignNpc="piet_supplier";return;}}
 public void guide(String id,boolean selling){tab=selling?1:0;filter="전체";page=selected=0;quantity=1;List<TownCommerce.Offer> offers=rows();for(int i=0;i<offers.size();i++)if(offers.get(i).id.equals(id)){selected=i;page=i/4;notice="학습 목표 · "+offers.get(i).name+" 1개 "+(selling?"판매":"구매")+" · 금액 확인 후 진행";break;}}
 private String[] tabs(){return def.kind==TownInteriorDef.Kind.BANK?new String[]{"입금","출금","물품 보관","물품 찾기"}:def.kind==TownInteriorDef.Kind.CHURCH?new String[]{"회복"}:new String[]{"구매","판매"};}
 private List<TownCommerce.Offer> rows(){List<TownCommerce.Offer> out=new ArrayList<>();if(def.kind==TownInteriorDef.Kind.BANK){if(tab<2){out.add(new TownCommerce.Offer("GOLD","Gold","은행",1,"1 Gold 단위 입금·출금"));return out;}Map<String,Integer> inv=tab==2?state.rpg().inventory():state.rpg().bankInventory();for(String id:inv.keySet()){if(tab==2&&state.rpg().equipment().containsValue(id))continue;RpgProgressionState.ItemDefinition item=state.rpg().itemDefinitions().get(id);out.add(new TownCommerce.Offer(id,item.name,"은행",0,"보관 수수료 없음"));}return out;}
  if(def.kind==TownInteriorDef.Kind.CHURCH){out.add(new TownCommerce.Offer("HEAL","생명과 마력 회복","성당",50,"현재 HP와 MP를 최대치로 회복합니다."));return out;}
  for(TownCommerce.Offer o:TownCommerce.offers(def.kind))if((tab==0||(TownCommerce.sellPrice(o.id)>0&&state.rpg().inventory().getOrDefault(o.id,0)>0))&&("전체".equals(filter)||filter.equals(o.category)))out.add(o);return out;}
 private TownCommerce.Offer chosen(){List<TownCommerce.Offer> r=rows();return selected>=0&&selected<r.size()?r.get(selected):null;}
 private TownCommerce.Operation operation(){return def.kind==TownInteriorDef.Kind.CHURCH?TownCommerce.Operation.HEAL:def.kind==TownInteriorDef.Kind.BANK?new TownCommerce.Operation[]{TownCommerce.Operation.DEPOSIT_GOLD,TownCommerce.Operation.WITHDRAW_GOLD,TownCommerce.Operation.DEPOSIT_ITEM,TownCommerce.Operation.WITHDRAW_ITEM}[tab]:tab==0?TownCommerce.Operation.BUY:TownCommerce.Operation.SELL;}
 private long unit(TownCommerce.Offer o){return tab==1&&(def.kind==TownInteriorDef.Kind.REAGENT||def.kind==TownInteriorDef.Kind.EQUIPMENT)?TownCommerce.sellPrice(o.id):o.price;}
 public void draw(Canvas c,float offset){if(!open)return;c.save();c.translate(offset,0);fill(c,0,0,960,540,0x9c000000);wood(c,245,58,925,426);label(c,campaignNpc==null?def.title:"피에트 보급점",513,86,18,0xffffd493);label(c,"×",895,86,24,0xffefdbb8);
  if(campaignNpc!=null){c.save();c.translate(50,110);c.scale(3,3);new NpcActorRenderer(context).draw(c,campaignNpc,30,90,CharacterRenderer.Direction.SE,CharacterRenderer.State.IDLE,0);c.restore();}else if(portraits!=null){int ix=def.kind.ordinal(),halfW=portraits.getWidth()/2,halfH=portraits.getHeight()/2;Rect src=new Rect(ix%2*halfW,ix/2*halfH,(ix%2+1)*halfW,(ix/2+1)*halfH);c.drawBitmap(portraits,src,new RectF(-37,108,281,426),p);}wood(c,52,392,211,425);label(c,campaignNpc==null?def.npcName:NpcIdentity.forId(campaignNpc).name,90,415,16,0xffead8ac);
  String[] tabs=tabs();for(int i=0;i<tabs.length;i++){fill(c,268+i*145,97,404+i*145,126,i==tab?0xff4b6641:0xff3d2b1e);label(c,tabs[i],285+i*145,118,13,0xfff1dfb6);}
  if(def.kind==TownInteriorDef.Kind.REAGENT||def.kind==TownInteriorDef.Kind.EQUIPMENT){String[] cats=def.kind==TownInteriorDef.Kind.REAGENT?new String[]{"전체","시약류","리콜류"}:new String[]{"전체","무기","방어구","장신구"};for(int i=0;i<cats.length;i++){fill(c,268+i*88,131,350+i*88,154,cats[i].equals(filter)?0xff695332:0xff2a211a);label(c,cats[i],280+i*88,147,11,0xffdacbaa);}}
  List<TownCommerce.Offer> rows=rows();for(int i=0;i<(def.kind==TownInteriorDef.Kind.CHURCH?1:4);i++){int ix=page*4+i;float y=162+i*43;fill(c,268,y,631,y+40,ix==selected?0xff655035:0xff2b2119);if(ix>=rows.size())continue;TownCommerce.Offer o=rows.get(ix);Bitmap b=icon(o.id);if(b!=null){float sc=Math.min(28f/b.getWidth(),28f/b.getHeight());c.drawBitmap(b,null,new RectF(279,y+6,279+b.getWidth()*sc,y+6+b.getHeight()*sc),p);}label(c,o.name,316,y+19,12,0xffefdfbf);label(c,amounts.format(unit(o))+" G",550,y+30,11,0xffd3ba89);}
  fill(c,643,158,899,335,0xff211911);TownCommerce.Offer o=chosen();if(o!=null){label(c,o.name,658,185,14,0xfff1d591);wrapped(c,o.description,658,208,225,11,0xffd5c7ac);RpgProgressionState.ItemDefinition item=state.rpg().itemDefinitions().get(o.id);if(item!=null&&item.equippable()){label(c,"레벨 "+item.requiredLevel+"  · "+item.equipSlot,658,245,11,0xffc9b996);String detail=modifierText(item);if(!detail.isEmpty())label(c,detail,658,260,11,0xffdfc47f);}int own=state.rpg().inventory().getOrDefault(o.id,0),stored=state.rpg().bankInventory().getOrDefault(o.id,0);if(def.kind==TownInteriorDef.Kind.BANK&&tab<2)label(c,"소지금 "+amounts.format(state.rpg().gold())+" Gold",658,278,11,0xffcbbb9a);else if(def.kind!=TownInteriorDef.Kind.CHURCH)label(c,"보유 "+own+"개 · 보관 "+stored+"개",658,278,10,0xffcbbb9a);if(def.kind!=TownInteriorDef.Kind.CHURCH){button(c,653,285,701,316,"−");button(c,707,283,840,317,amounts.format(quantity)+"  입력");button(c,846,285,888,316,"+");button(c,756,321,888,348,def.kind==TownInteriorDef.Kind.BANK&&tab<2?"1 / 100 / 1000":"1 / 10 / 100");}else{label(c,"HP "+state.player().hp+" / "+state.player().maxHp,658,280,12,0xffd9cbae);label(c,"MP "+state.player().mp+" / "+state.player().maxMp,658,304,12,0xffd9cbae);}}
  if(def.kind!=TownInteriorDef.Kind.CHURCH){label(c,"〈 이전",282,350,12,0xffd7c19e);label(c,(page+1)+" / "+Math.max(1,(rows.size()+3)/4),425,350,12,0xffd7c19e);label(c,"다음 〉",550,350,12,0xffd7c19e);}else{label(c,"회복의 축복",286,238,16,0xffead29c);label(c,"생명력과 마력을 온전히 회복합니다.",286,266,12,0xffd5c8ad);label(c,"HP",286,294,12,0xffd5c8ad);fill(c,318,280,601,294,0xff251c15);fill(c,318,280,318+283f*state.player().hp/Math.max(1,state.player().maxHp),294,0xff99604d);label(c,"MP",286,322,12,0xffd5c8ad);fill(c,318,308,601,322,0xff251c15);fill(c,318,308,318+283f*state.player().mp/Math.max(1,state.player().maxMp),322,0xff516f85);}if(rows.isEmpty())label(c,def.kind==TownInteriorDef.Kind.BANK?"보관할 물품이 없습니다.":"판매할 상품이 없습니다.",286,218,13,0xffc6b692);label(c,"보유 "+amounts.format(state.rpg().gold())+" G",274,385,13,0xffe4cc93);if(def.kind==TownInteriorDef.Kind.BANK)label(c,"예금 "+amounts.format(state.rpg().bankGold())+" G",462,385,12,0xffd8c28e);if(o!=null){label(c,"총액 "+amounts.format(unit(o)*(def.kind==TownInteriorDef.Kind.CHURCH?1:quantity))+" G",651,356,12,0xffe9cd91);button(c,651,367,899,406,tabs[tab]+" 확인");}
  wood(c,30,437,925,525);label(c,campaignNpc==null?def.npcName:NpcIdentity.forId(campaignNpc).name,48,461,12,0xff89c37e);label(c,notice,48,487,13,0xffe4d7bd);button(c,814,488,903,514,"닫기");
  if(confirm&&o!=null){fill(c,0,0,960,540,0x99000000);wood(c,280,177,710,351);label(c,tabs[tab]+" · "+o.name,309,209,16,0xfff0d59a);label(c,"수량 "+(def.kind==TownInteriorDef.Kind.CHURCH?1:quantity)+" · 총액 "+amounts.format(unit(o)*(def.kind==TownInteriorDef.Kind.CHURCH?1:quantity))+" G",309,246,14,0xffe1ceb0);button(c,310,285,474,327,"취소");button(c,501,285,679,327,"확인");}c.restore();}
 public boolean touch(float x,float y,float offset,TownCommerce.Durability durable){if(!open)return false;x-=offset;if(confirm){if(hit(x,y,310,285,474,327))confirm=false;else if(hit(x,y,501,285,679,327)){TownCommerce.Offer o=chosen();TownCommerce.Result r=o==null?TownCommerce.Result.INVALID:TownCommerce.transact(state,def.kind,operation(),o.id,def.kind==TownInteriorDef.Kind.CHURCH?1:quantity,durable);notice=r==TownCommerce.Result.OK?"거래가 완료되었습니다.":r==TownCommerce.Result.SAVE_FAILED?"저장 실패 · 거래를 취소했습니다.":r==TownCommerce.Result.INSUFFICIENT_GOLD?"골드가 부족합니다.":r==TownCommerce.Result.EQUIPPED?"장착 중인 장비는 해제한 뒤 거래해 주세요.":r==TownCommerce.Result.NOT_OWNED?"보유 수량이 부족합니다.":"거래 조건 또는 수량을 확인해 주세요.";confirm=false;selected=Math.min(selected,Math.max(0,rows().size()-1));page=selected/4;}return true;}
  if(hit(x,y,875,58,925,97)||hit(x,y,814,488,903,525)){close();return true;}for(int i=0;i<tabs().length;i++)if(hit(x,y,268+i*145,97,404+i*145,126)){tab=i;page=selected=0;quantity=1;return true;}
  if(def.kind==TownInteriorDef.Kind.REAGENT||def.kind==TownInteriorDef.Kind.EQUIPMENT){String[] cats=def.kind==TownInteriorDef.Kind.REAGENT?new String[]{"전체","시약류","리콜류"}:new String[]{"전체","무기","방어구","장신구"};for(int i=0;i<cats.length;i++)if(hit(x,y,268+i*88,131,350+i*88,154)){filter=cats[i];selected=page=0;return true;}}
  for(int i=0;i<4;i++)if(hit(x,y,268,162+i*43,631,202+i*43)&&page*4+i<rows().size()){selected=page*4+i;quantity=1;return true;}
  if(hit(x,y,268,335,380,362)){page=Math.max(0,page-1);selected=page*4;}else if(hit(x,y,525,335,632,362)){page=Math.min(Math.max(0,(rows().size()-1)/4),page+1);selected=page*4;}else if(hit(x,y,653,285,701,316))quantity=Math.max(1,quantity-1);else if(hit(x,y,707,283,840,317)){TownCommerce.Offer pick=chosen();if(pick!=null){final int token=session,index=selected,mode=tab;TownQuantityDialog.show(context,pick.name,quantity,n->{if(open&&!confirm&&session==token&&selected==index&&tab==mode&&chosen()!=null&&pick.id.equals(chosen().id)){quantity=n;}});}}else if(hit(x,y,846,285,888,316))quantity=Math.min(999999,quantity+1);else if(hit(x,y,756,321,888,348)){quantity=def.kind==TownInteriorDef.Kind.BANK&&tab<2?(quantity<100?100:quantity<1000?1000:1):(quantity<10?10:quantity<100?100:1);}else if(hit(x,y,651,367,899,406)&&chosen()!=null)confirm=true;return true;}
 private String modifierText(RpgProgressionState.ItemDefinition item){StringBuilder b=new StringBuilder();String[] keys={"MinATK","MaxATK","AC","MAGIC_DEFENSE","HP","MP","HIT","DAM","STR","INT","WIS","CON","DEX"};for(String key:keys){Integer v=item.statModifiers.get(key);if(v==null||v==0)continue;if(b.length()>0)b.append("  ·  ");b.append(key.equals("MAGIC_DEFENSE")?"마방":key).append(v>0?" +":" ").append(v);}return b.toString();}
 private static boolean hit(float x,float y,float l,float t,float r,float b){return x>=l&&x<=r&&y>=t&&y<=b;}
 private void fill(Canvas c,float l,float t,float r,float b,int color){p.setStyle(Paint.Style.FILL);p.setColor(color);c.drawRect(l,t,r,b,p);}
 private void wood(Canvas c,float l,float t,float r,float b){
  p.setStyle(Paint.Style.FILL);p.setColor(0xffffffff);p.setShader(new LinearGradient(l,t,r,b,new int[]{0xff755130,0xff322319,0xff654527},null,Shader.TileMode.CLAMP));c.drawRoundRect(new RectF(l,t,r,b),7,7,p);p.setShader(null);
  for(int y=(int)t+8;y<b-7;y+=4){p.setColor(y%8==0?0x188f7146:0x1421140a);c.drawLine(l+7,y,r-7,y,p);}
  p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0xff21160f);c.drawRoundRect(new RectF(l,t,r,b),7,7,p);p.setColor(0xffb49460);c.drawRoundRect(new RectF(l+3,t+3,r-3,b-3),5,5,p);p.setColor(0xff3a2719);c.drawRoundRect(new RectF(l+6,t+6,r-6,b-6),3,3,p);p.setStyle(Paint.Style.FILL);
  if(r-l>150&&b-t>60)for(float x:new float[]{l+9,r-9})for(float y:new float[]{t+9,b-9}){p.setColor(0xff21150d);c.drawCircle(x,y,4,p);p.setColor(0xffbd9562);c.drawCircle(x-1,y-1,2,p);}
 }
 private void wrapped(Canvas c,String s,float x,float y,float width,int size,int color){p.setTextSize(size);int start=0;for(int row=0;row<2&&start<s.length();row++){int end=start+1;while(end<=s.length()&&p.measureText(s,start,end)<=width)end++;end=Math.max(start+1,end-1);label(c,s.substring(start,end),x,y+row*15,size,color);start=end;}}
 private Bitmap icon(String id){if(iconCache.containsKey(id))return iconCache.get(id);Bitmap b=reagent.get(id);RpgProgressionState.ItemDefinition item=state.rpg().itemDefinitions().get(id);if(b==null)b=ItemIconCatalog.reagent(id);if(b==null)b=sourceIcons.get(item);iconCache.put(id,b);return b;}

 private void button(Canvas c,float l,float t,float r,float b,String s){wood(c,l,t,r,b);label(c,s,l+12,t+(b-t)*.67f,12,0xffe4d2aa);}
 private void label(Canvas c,String s,float x,float y,int size,int color){p.setTypeface(Typeface.DEFAULT);p.setTextSize(size);p.setColor(color);c.drawText(s,x,y,p);}
}
