package com.projectdark.mobile.world;
import android.content.Context;import android.graphics.*;import org.json.*;import java.io.*;import java.util.*;
public final class TownInteriorRenderer {
 private final Bitmap props,tiles;private final Paint p=new Paint();private final Map<String,Rect> regions=new HashMap<>();
 public TownInteriorRenderer(Context c){Bitmap a=null,b=null;try(InputStream in=c.getAssets().open("interiors/v84/props.png")){a=BitmapFactory.decodeStream(in);}catch(IOException e){}try(InputStream in=c.getAssets().open("interiors/v84/tiles.png")){b=BitmapFactory.decodeStream(in);}catch(IOException e){}props=a;tiles=b;p.setFilterBitmap(false);try(InputStream in=c.getAssets().open("interiors/v84/atlas.json")){JSONObject o=new JSONObject(readText(in)).getJSONObject("props");for(Iterator<String> it=o.keys();it.hasNext();){String k=it.next();JSONObject r=o.getJSONObject(k);regions.put(k,new Rect(r.getInt("x"),r.getInt("y"),r.getInt("x")+r.getInt("width"),r.getInt("y")+r.getInt("height")));}Rect s=regions.get("church_wall_sw");regions.put("church_wall_se",s);}catch(Exception e){throw new IllegalStateException("Interior atlas",e);}}
 private static String readText(InputStream in)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];for(int n;(n=in.read(b))!=-1;)out.write(b,0,n);return out.toString("UTF-8");}
 public boolean ready(){return props!=null&&tiles!=null&&regions.size()>=16;}
 public void ground(Canvas c,WorldRuntimeAdapter w,TownInteriorDef d){c.drawColor(0xff100c09);for(int u=0;u<12;u++)for(int v=0;v<12;v++){WorldCameraTransform.Point q=w.worldToScreen(TownInteriorDef.x(u,v),TownInteriorDef.y(u,v));int i=d.floor(u,v);c.drawBitmap(tiles,new Rect(i*64,0,i*64+64,32),new RectF(q.x-32,q.y-16,q.x+32,q.y+16),p);}WorldCameraTransform.Point e=w.worldToScreen(d.exitX(),d.exitY());p.setColor(0xffcbb574);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);c.drawOval(new RectF(e.x-22,e.y-9,e.x+22,e.y+9),p);p.setStyle(Paint.Style.FILL);}
 public void prop(Canvas c,WorldRuntimeAdapter w,TownInteriorDef.Prop o){Rect src=regions.get(o.asset);if(src==null||props==null)return;WorldCameraTransform.Point q=w.worldToScreen(o.x(),o.y());float h=o.width*src.height()/src.width();if("church_wall_se".equals(o.asset)){c.save();c.scale(-1,1,q.x,q.y);c.drawBitmap(props,src,new RectF(q.x-o.width/2,q.y-h,q.x+o.width/2,q.y),p);c.restore();}else c.drawBitmap(props,src,new RectF(q.x-o.width/2,q.y-h,q.x+o.width/2,q.y),p);}
}
