package com.projectdark.mobile.world;

import android.graphics.RectF;
import com.projectdark.mobile.CharacterRenderer;
import com.projectdark.mobile.RuntimeState;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** World-owned integration surface. A logical isometric step is an atomic transition. */
public final class WorldRuntimeAdapter implements WorldMoveTargetController.NavigationWorld, WorldMoveTargetController.Walker {
  public static final class FrameSnapshot {
    public final float playerWorldX,playerWorldY,playerScreenX,playerScreenY,cameraX,cameraY,presentationWalkClock;
    public final WorldMoveTargetController.Snapshot movement;
    public final WorldMapProjection.Portal overlappingPortal;
    FrameSnapshot(float wx,float wy,float sx,float sy,float cx,float cy,float walkClock,WorldMoveTargetController.Snapshot movement,WorldMapProjection.Portal portal){playerWorldX=wx;playerWorldY=wy;playerScreenX=sx;playerScreenY=sy;cameraX=cx;cameraY=cy;presentationWalkClock=walkClock;this.movement=movement;overlappingPortal=portal;}
  }
  private final RuntimeState runtime; private final WorldMapProjection map; private final WorldCameraTransform camera; private final WorldMoveTargetController movement; private final WorldStepInterpolator presentation; private final List<WorldMoveTargetController.TileCenter> navigationTiles; private float presentationWalkClock;
  public WorldRuntimeAdapter(RuntimeState runtime,float viewportWidth,float viewportHeight){if(runtime==null)throw new IllegalArgumentException("runtime required");if(runtime.bootMode()!=RuntimeState.BootMode.MILLES)throw new IllegalArgumentException("Milles WorldRuntimeAdapter requires MILLES boot mode");this.runtime=runtime;map=WorldMapProjection.from(runtime.world());List<WorldMoveTargetController.TileCenter> centers=new ArrayList<>();for(AdaptedMillesIsometricTileLayer.Tile tile:map.tiles())centers.add(new WorldMoveTargetController.TileCenter(tile.centerX,tile.centerY));navigationTiles=Collections.unmodifiableList(centers);snapPlayerToNearestTraversableTile();camera=map.newCamera(viewportWidth,viewportHeight);camera.snapTo(runtime.player().x,runtime.player().y);movement=new WorldMoveTargetController(this,this);presentation=new WorldStepInterpolator(WorldMoveTargetController.TILE_STEP_SECONDS,runtime.player().x,runtime.player().y);CharacterRenderer.setPresentationWalkClock(0f);}
  public RuntimeState runtime(){return runtime;} public WorldMapProjection map(){return map;} public WorldCameraTransform camera(){return camera;} public WorldMoveTargetController movement(){return movement;}
  public WorldMoveTargetController.Snapshot requestGroundScreenTap(float sx,float sy){WorldCameraTransform.Point w=camera.screenToWorld(sx,sy);return movement.requestGroundMove(w.x,w.y);} public WorldMoveTargetController.Snapshot requestGroundWorld(float x,float y){return movement.requestGroundMove(x,y);}
  public WorldMoveTargetController.Snapshot step(WorldMoveTargetController.Direction d){if(presentation.active())return movement.snapshot();WorldMoveTargetController.Snapshot r=movement.step(d);beginPresentationIfMoved();return r;}
  public WorldMoveTargetController.Snapshot requestNpcApproach(String id){RuntimeState.Npc n=findNpc(id);if(n==null)throw new IllegalArgumentException("unknown npcId: "+id);return movement.requestNpcApproach(n.id,n.x,n.y,WorldMoveTargetController.DEFAULT_NPC_APPROACH_TOLERANCE);}
  public WorldMoveTargetController.Snapshot requestMonsterApproach(String id,float tolerance){RuntimeState.Monster m=findMonster(id);if(m==null||!m.alive)throw new IllegalArgumentException("unknown or defeated monsterId: "+id);return movement.requestMonsterApproach(m.id,m.x,m.y,Math.max(1f,tolerance));}
  public WorldMoveTargetController.Snapshot cancelForDirectInput(){return movement.cancelForDirectInput();} public WorldMoveTargetController.Snapshot cancelForAction(){WorldMoveTargetController.Snapshot r=movement.cancelForAction();presentation.snap(runtime.player().x,runtime.player().y);return r;} public WorldMoveTargetController.Snapshot cancel(){WorldMoveTargetController.Snapshot r=movement.cancel();presentation.snap(runtime.player().x,runtime.player().y);return r;}
  public FrameSnapshot tickNavigation(float dt){float remaining=Math.max(0f,dt);WorldMoveTargetController.Snapshot move=movement.snapshot();while(remaining>0f){if(presentation.active()){float before=remaining;remaining=presentation.advance(remaining);float consumed=Math.max(0f,before-remaining);presentationWalkClock+=consumed;CharacterRenderer.setPresentationWalkClock(presentationWalkClock);if(remaining>=before-.000001f)break;continue;}if(move.status!=WorldMoveTargetController.Status.MOVING)break;move=movement.tick(WorldMoveTargetController.TILE_STEP_SECONDS);beginPresentationIfMoved();if(!presentation.active())break;}camera.follow(presentation.x(),presentation.y());return frame(move);}
  public void snapCameraToPlayer(){snapPlayerToNearestTraversableTile();presentation.snap(runtime.player().x,runtime.player().y);presentationWalkClock=0f;CharacterRenderer.setPresentationWalkClock(0f);camera.snapTo(runtime.player().x,runtime.player().y);} public float presentationPlayerX(){return presentation.x();} public float presentationPlayerY(){return presentation.y();} public float presentationWalkClock(){return presentationWalkClock;} public boolean presentationMoving(){return presentation.active();} public WorldCameraTransform.Point worldToScreen(float x,float y){return camera.worldToScreen(x,y);} public WorldCameraTransform.Point screenToWorld(float x,float y){return camera.screenToWorld(x,y);} public FrameSnapshot snapshot(){return frame(movement.snapshot());}
  private FrameSnapshot frame(WorldMoveTargetController.Snapshot move){WorldCameraTransform.Point p=camera.worldToScreen(presentation.x(),presentation.y());return new FrameSnapshot(presentation.x(),presentation.y(),p.x,p.y,camera.cameraX(),camera.cameraY(),presentationWalkClock,move,portalAt(runtime.player().x,runtime.player().y));}
  private void beginPresentationIfMoved(){if(Math.abs(presentation.x()-runtime.player().x)>.0001f||Math.abs(presentation.y()-runtime.player().y)>.0001f)presentation.begin(runtime.player().x,runtime.player().y);}
  public WorldMapProjection.Portal portalAt(float x,float y){for(WorldMapProjection.Portal p:map.portals())if(p.contains(x,y))return p;return null;} private RuntimeState.Npc findNpc(String id){if(id==null)return null;for(RuntimeState.Npc n:runtime.npcs())if(id.equals(n.id))return n;return null;} private RuntimeState.Monster findMonster(String id){if(id==null)return null;for(RuntimeState.Monster m:runtime.monsters())if(id.equals(m.id))return m;return null;}
  @Override public List<WorldMoveTargetController.TileCenter> navigationTiles(){return navigationTiles;}
  @Override public boolean canPlayerOccupy(float x,float y){float r=RuntimeState.PLAYER_RADIUS;if(x-r<map.bounds().minX||x+r>map.bounds().maxX||y-r<map.bounds().minY||y+r>map.bounds().maxY)return false;for(RectF o:runtime.obstacles())if(x+r>o.left&&x-r<o.right&&y+r>o.top&&y-r<o.bottom)return false;for(RuntimeState.Npc n:runtime.npcs())if(distance(x,y,n.x,n.y)<r+RuntimeState.NPC_RADIUS+2f)return false;for(RuntimeState.Monster m:runtime.monsters())if(m.alive&&distance(x,y,m.x,m.y)<r+RuntimeState.MONSTER_RADIUS+3f)return false;return true;}
  @Override public float worldX(){return runtime.player().x;} @Override public float worldY(){return runtime.player().y;}
  @Override public boolean moveToAdjacentTile(float destinationX,float destinationY,WorldMoveTargetController.Direction direction){float startX=runtime.player().x,startY=runtime.player().y;if(WorldMoveTargetController.Direction.between(startX,startY,destinationX,destinationY)!=direction)return false;if(!canPlayerOccupy(destinationX,destinationY))return false;/* Atomic tile contract: collision is evaluated at the authored destination, never at a synthetic X-only half-step. RuntimeState's axis resolver is bypassed only after the destination has passed the authoritative occupancy gate. */runtime.player().x=destinationX;runtime.player().y=destinationY;return true;}
  private void snapPlayerToNearestTraversableTile(){WorldMoveTargetController.TileCenter best=null;float bd=Float.MAX_VALUE;for(WorldMoveTargetController.TileCenter t:navigationTiles){if(!canPlayerOccupy(t.x,t.y))continue;float dx=t.x-runtime.player().x,dy=t.y-runtime.player().y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=t;}}if(best==null)throw new IllegalStateException("no traversable spawn tile");runtime.player().x=best.x;runtime.player().y=best.y;}
  private static float distance(float ax,float ay,float bx,float by){float dx=ax-bx,dy=ay-by;return(float)Math.sqrt(dx*dx+dy*dy);}
}
