package com.projectdark.mobile;
import static org.junit.Assert.*;
import android.graphics.*;import com.projectdark.mobile.world.*;import java.util.*;import java.lang.reflect.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=34,manifest=Config.NONE) @GraphicsMode(GraphicsMode.Mode.NATIVE)
public class DeviceRepairV114Test {
 @Before public void setup(){for(String n:new String[]{"project_dark_f5m_v1","project_dark_journal_v1","project_dark_skill_test_v1"})RuntimeEnvironment.getApplication().getSharedPreferences(n,0).edit().clear().commit();F5mSaveStore.install(RuntimeEnvironment.getApplication());}
 @Test public void terrainBroadPhaseMatchesIndependentLinearOracle(){Random rng=new Random(114);List<RectF> obstacles=new ArrayList<>();for(int i=0;i<600;i++){float x=rng.nextInt(5000)-500,y=rng.nextInt(2500)-500;obstacles.add(new RectF(x,y,x+4+rng.nextInt(180),y+4+rng.nextInt(180)));}TerrainObstacleIndex index=new TerrainObstacleIndex(obstacles);for(int i=0;i<20000;i++){float x=rng.nextFloat()*5500-500,y=rng.nextFloat()*3000-500,r=1+rng.nextFloat()*30;boolean expected=false;for(RectF o:obstacles)if(x+r>o.left&&x-r<o.right&&y+r>o.top&&y-r<o.bottom){expected=true;break;}assertEquals(expected,index.blocked(x,y,r));}}
 @Test public void actualForestEntryAndWarmGateChecksHaveBoundedLatency()throws Exception{
  GameView v=new GameView(RuntimeEnvironment.getApplication());v.layout(0,0,1536,864);long start=System.nanoTime();PoteReferenceV113Test.invoke(v,"enterPoteField");long entryMs=(System.nanoTime()-start)/1000000;RuntimeState s=TownInteriorTest.field(v,"state");assertEquals(72,s.monsters().size());assertTrue("cold entry JVM ms="+entryMs,entryMs<5000);
  CampaignWorld.forward(s.currentMapId());CampaignWorld.backward(s.currentMapId());start=System.nanoTime();for(int i=0;i<10000;i++){CampaignWorld.forward(s.currentMapId());CampaignWorld.backward(s.currentMapId());}long gatesMs=(System.nanoTime()-start)/1000000;assertTrue("warm gates ms="+gatesMs,gatesMs<1000);System.out.println("V114_ENTRY_JVM_MS="+entryMs+"; GATE_20000_CALLS_MS="+gatesMs+"; PHONE_PENDING");
  start=System.nanoTime();for(int i=0;i<1000;i++)for(RuntimeState.Monster m:s.monsters())assertTrue(s.isMonsterTileCenter(m.x,m.y));long membershipMs=(System.nanoTime()-start)/1000000;assertTrue("72000 AI membership calls ms="+membershipMs,membershipMs<1500);System.out.println("V114_AI_MEMBERSHIP_72000_MS="+membershipMs);
  WorldRuntimeAdapter world=TownInteriorTest.field(v,"poteFieldAdapter");PoteCampaignMapDef d=PoteCampaignMapDef.forId(s.currentMapId());world.camera().snapTo(d.bridgeX(),d.bridgeY());PoteReferenceV113Test.capture(v,"v114-creek");
 }
 @Test public void npcRoleButtonsCannotHealOrSellFromGuidesMentorsInvestigatorsOrAltars()throws Exception{
  GameView v=new GameView(RuntimeEnvironment.getApplication());v.layout(0,0,1536,864);RuntimeState s=TownInteriorTest.field(v,"state");s.rpg().grantAdaptedReward(5000000,1000);assertTrue(s.rpg().chooseInitialJob("WARRIOR"));PoteReferenceV113Test.invoke(v,"enterPoteField");Method change=GameView.class.getDeclaredMethod("changeCampaignMap",String.class,boolean.class);change.setAccessible(true);change.invoke(v,CampaignWorld.PIET,false);
  InteractionController interaction=TownInteriorTest.field(v,"interaction");Method handle=GameView.class.getDeclaredMethod("handleCampaignDialogue",float.class,float.class);handle.setAccessible(true);
  for(RuntimeState.Npc npc:s.npcs()){if(npc.id.equals("piet_supplier"))continue;s.player().x=npc.x;s.player().y=npc.y+24;s.player().hp=1;s.player().mp=0;long gold=s.rpg().gold();interaction.request(s,npc);assertTrue(interaction.dialogOpen());for(int button=0;button<3;button++)handle.invoke(v,240f+130*button,430f);assertEquals("no generic heal "+npc.id,1,s.player().hp);assertEquals("no generic MP "+npc.id,0,s.player().mp);assertEquals(gold,s.rpg().gold().longValue());}
  RuntimeState.Npc merchant=null;for(RuntimeState.Npc n:s.npcs())if(n.id.equals("piet_supplier"))merchant=n;assertNotNull(merchant);s.player().x=merchant.x;s.player().y=merchant.y+24;interaction.request(s,merchant);PoteReferenceV113Test.capture(v,"v114-supplier-dialogue");long gold=s.rpg().gold();handle.invoke(v,370f,430f);assertEquals(gold-20,s.rpg().gold().longValue());
  interaction.dismissDialog();SkillWindow skills=TownInteriorTest.field(v,"skillWindow");v.setSkillTestMode(true);skills.open=true;skills.showJob("전사");PoteReferenceV113Test.capture(v,"v114-skill-window");skills.close();QuestJournalModel model=TownInteriorTest.field(v,"questJournalModel");QuestJournalWindow journal=TownInteriorTest.field(v,"questJournalWindow");List<QuestJournalModel.Row> rows=model.rows(TownInteriorTest.field(v,"f5mQuest"),TownInteriorTest.field(v,"quest2"),true,s.rpg());journal.open(rows,null);Field open=GameView.class.getDeclaredField("questJournalOpen");open.setAccessible(true);open.setBoolean(v,true);PoteReferenceV113Test.capture(v,"v114-quest-window");
 }
}
