package com.projectdark.mobile;

import static org.junit.Assert.*;
import android.content.Context;
import android.graphics.*;
import android.view.MotionEvent;
import com.projectdark.mobile.world.*;
import java.io.*;
import java.util.*;
import org.json.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.*;

/** Real book/stat/shop controls from a completed-opening fixture; full journey is CampaignProgressTest. */
@RunWith(RobolectricTestRunner.class) @Config(sdk=34,manifest=Config.NONE) @GraphicsMode(GraphicsMode.Mode.NATIVE)
public class OnboardingUiTest {
 Context context;
 @Before public void reset(){context=RuntimeEnvironment.getApplication();for(String name:new String[]{"project_dark_f5m_v1","project_dark_skill_test_v1","project_dark_journal_v1"})context.getSharedPreferences(name,0).edit().clear().commit();F5mSaveStore.install(context);}
 GameView start(String job)throws Exception{GameView v=new GameView(context);v.layout(0,0,960,540);RuntimeState s=TownInteriorTest.field(v,"state");((F5mAdaptedPrologueQuest)TownInteriorTest.field(v,"f5mQuest")).restore(F5mAdaptedPrologueQuest.State.COMPLETED,1);((GrowthQuest2)TownInteriorTest.field(v,"quest2")).restore(GrowthQuest2.State.COMPLETED,3);RpgProgressionState r=s.rpg();r.grantAdaptedReward(25300,450);r.campaign().syncOpening(true,true);assertTrue(r.chooseInitialJob(job));SkillBook b=TownInteriorTest.field(v,"skillBook");assertTrue(r.campaign().accept("M03",r,b));assertTrue(r.campaign().claim("M03",r));v.setSkillTestMode(true);return v;}
 static void tap(GameView v,float x,float y){QuestJournalTest.gesture(v,x,y);}
 static void capture(GameView v,String name)throws Exception{Bitmap b=Bitmap.createBitmap(v.getWidth(),v.getHeight(),Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));File f=new File("build/reports/device-review/v110-"+name+".png");f.getParentFile().mkdirs();try(OutputStream out=new FileOutputStream(f)){assertTrue(b.compress(Bitmap.CompressFormat.PNG,100,out));}b.recycle();}
 @Test public void fiveJobsLearnAndRegisterThroughRealButtonsWithoutAutomaticOwnership()throws Exception{
  for(String job:CampaignProgress.JOBS){reset();GameView v=start(job);RuntimeState s=TownInteriorTest.field(v,"state");RpgProgressionState r=s.rpg();SkillBook b=TownInteriorTest.field(v,"skillBook");String id=CampaignProgress.beginnerSkill(job);assertFalse(b.owned(id));
   tap(v,80,150);assertTrue((Boolean)TownInteriorTest.field(v,"statsOpen"));int stat=job.equals("MAGE")||job.equals("CLERIC")?2:0;tap(v,724,150+stat*30);if(job.equals("MAGE"))for(int i=0;i<3;i++)tap(v,724,180);assertEquals(CampaignProgress.Status.REPORT,r.campaign().status(CampaignProgress.find("T01"),r));capture(v,"stats-"+job);tap(v,911,91);
   tap(v,80,150);assertTrue((Boolean)TownInteriorTest.field(v,"questJournalOpen"));tap(v,680,444);assertFalse("learning guide switches from preview to actual ownership",b.testAccess());assertEquals(id,((SkillWindow)TownInteriorTest.field(v,"skillWindow")).selectedId);assertFalse(b.owned(id));long gold=r.gold();capture(v,"learn-"+job);tap(v,710,400);assertTrue("explicit learn control acquires "+id,b.owned(id));assertEquals(gold-50,r.gold().longValue());tap(v,710,400);assertEquals("duplicate input cannot repay",gold-50,r.gold().longValue());TownInteriorTest.tick(v,1);assertEquals(CampaignProgress.Status.REPORT,r.campaign().status(CampaignProgress.find("T02"),r));tap(v,915,60);
   tap(v,80,150);tap(v,680,444);assertNull("learning never automatically fills a real slot",b.slot(0));tap(v,850,400);tap(v,676,460);assertEquals(id,b.slot(0));assertEquals(CampaignProgress.Status.REPORT,r.campaign().status(CampaignProgress.find("T03"),r));capture(v,"registered-"+job);v.pause();F5mSaveStore.install(context);GameView restored=new GameView(context);SkillBook rb=TownInteriorTest.field(restored,"skillBook");RuntimeState rs=TownInteriorTest.field(restored,"state");assertTrue(rb.owned(id));assertEquals(id,rb.slot(0));assertEquals("T03",rs.rpg().campaign().activeId());assertEquals(CampaignProgress.Status.REPORT,rs.rpg().campaign().status(CampaignProgress.find("T03"),rs.rpg()));
  }
 }
 @Test public void wrongEarlyAllocationCanBeCorrectedWithoutExpGoldRewardOrSkillLoss()throws Exception{
  GameView v=start("MAGE");RuntimeState s=TownInteriorTest.field(v,"state");RpgProgressionState r=s.rpg();SkillBook b=TownInteriorTest.field(v,"skillBook");while(r.statPoints()>0)assertTrue(r.spendStat("STR"));int spent=r.str()-3;assertEquals(0,r.statPoints());long exp=CampaignProgress.earnedExp(r),gold=r.gold();tap(v,80,150);assertTrue((Boolean)TownInteriorTest.field(v,"statsOpen"));tap(v,667,342);assertEquals(3,r.str());assertEquals(spent,r.statPoints());assertEquals(exp,CampaignProgress.earnedExp(r));assertEquals(gold,r.gold().longValue());assertFalse(b.owned(CampaignProgress.beginnerSkill("MAGE")));tap(v,724,210);for(int i=0;i<3;i++)tap(v,724,180);v.setSkillTestMode(false);assertTrue(new SkillAcquisition(b).quote(b.get(CampaignProgress.beginnerSkill("MAGE")),r).canLearn);capture(v,"stat-correction");v.pause();F5mSaveStore.install(context);RuntimeState restored=TownInteriorTest.field(new GameView(context),"state");assertEquals(6,restored.rpg().intel());assertEquals(4,restored.rpg().wis());assertEquals(0,restored.rpg().statPoints());assertEquals("T01",restored.rpg().campaign().activeId());
 }
 @Test public void actualQuickGuideWalksIntoShopFocusesProductAndDurablyCountsPurchase()throws Exception{
  GameView v=start("WARRIOR");RuntimeState s=TownInteriorTest.field(v,"state");CampaignProgress c=s.rpg().campaign();JSONObject saved=c.snapshot();saved.put("complete",new JSONArray().put("M01").put("M02").put("M03").put("T01").put("T02").put("T03").put("J01_WARRIOR"));assertTrue(c.restore(saved));
  tap(v,80,150);assertEquals("T04",c.activeId());for(int frame=0;frame<3000&&!((TownShopWindow)TownInteriorTest.field(v,"townWindow")).isOpen();frame++)TownInteriorTest.tick(v,1);assertEquals("milles_interior_weapon_shop",s.currentMapId());TownShopWindow shop=TownInteriorTest.field(v,"townWindow");assertTrue(shop.isOpen());assertEquals(11,((Integer)TownInteriorTest.field(shop,"selected")).intValue());capture(v,"guided-shoe-shop");long gold=s.rpg().gold();tap(v,780,387);assertEquals(gold,s.rpg().gold().longValue());tap(v,586,305);assertEquals(gold-150,s.rpg().gold().longValue());assertEquals(1,c.count(CampaignProgress.find("T04"),s.rpg()));assertEquals(CampaignProgress.Status.REPORT,c.status(CampaignProgress.find("T04"),s.rpg()));v.pause();F5mSaveStore.install(context);RuntimeState restored=TownInteriorTest.field(new GameView(context),"state");assertEquals("T04",restored.rpg().campaign().activeId());assertEquals(1,restored.rpg().campaign().count(CampaignProgress.find("T04"),restored.rpg()));
 }
 @Test public void failedTradeWrongItemAndFullHealthNeverManufactureCompletion()throws Exception{
  GameView v=start("WARRIOR");RuntimeState s=TownInteriorTest.field(v,"state");CampaignProgress c=s.rpg().campaign();JSONObject saved=c.snapshot();JSONArray done=new JSONArray();for(CampaignProgress.Def d:c.route("WARRIOR")){if(d.id.equals("T06"))break;done.put(d.id);}saved.put("complete",done);assertTrue(c.restore(saved));assertTrue(c.accept("T06",s.rpg(),TownInteriorTest.field(v,"skillBook")));long gold=s.rpg().gold();assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.REAGENT,TownCommerce.Operation.BUY,RpgProgressionState.B_SMALL_POTION_ITEM_ID,1,()->false));assertEquals(gold,s.rpg().gold().longValue());assertEquals(0,c.count(CampaignProgress.find("T06"),s.rpg()));assertEquals(TownCommerce.Result.OK,TownCommerce.transact(s,TownInteriorDef.Kind.REAGENT,TownCommerce.Operation.BUY,"IT_B_MP_POTION",1,()->true));assertEquals(0,c.count(CampaignProgress.find("T06"),s.rpg()));assertTrue(s.rpg().buySmallPotion());assertTrue(c.claim("T06",s.rpg()));assertTrue(c.accept("T07",s.rpg(),null));s.player().hp=s.player().maxHp;int owned=s.rpg().inventory().get(RpgProgressionState.B_SMALL_POTION_ITEM_ID);assertEquals(RpgProgressionState.UseResult.NO_EFFECT,s.rpg().useConsumable(RpgProgressionState.B_SMALL_POTION_ITEM_ID,s));assertEquals(owned,s.rpg().inventory().get(RpgProgressionState.B_SMALL_POTION_ITEM_ID).intValue());assertEquals(0,c.count(CampaignProgress.find("T07"),s.rpg()));
 }
 @Test public void quickPotionLessonLeavesShopAndRequiresActualFieldQuickslotUse()throws Exception{
  GameView v=start("WARRIOR");RuntimeState s=TownInteriorTest.field(v,"state");RpgProgressionState r=s.rpg();CampaignProgress c=r.campaign();JSONArray done=new JSONArray();for(CampaignProgress.Def d:c.route("WARRIOR")){if(d.id.equals("T09"))break;done.put(d.id);}assertTrue(c.restore(c.snapshot().put("complete",done)));s.applyDerivedGrowth();s.player().hp=s.player().maxHp;TownInteriorTest.enter(v,TownInteriorDef.forMap("milles_interior_potion_shop"));tap(v,80,150);assertEquals("T09",c.activeId());for(int n=0;n<1600&&!s.currentMapId().equals(WorldDef.ID);n++)TownInteriorTest.tick(v,1);assertEquals("guide exits the real shop before field potion input",WorldDef.ID,s.currentMapId());
  for(int n=0;n<1600&&s.player().hp>=s.player().maxHp;n++)TownInteriorTest.tick(v,1);assertTrue("real field AI must cause the loss, not a fixture damage injection",s.player().hp<s.player().maxHp);assertEquals(RpgProgressionState.UseResult.USED,r.useConsumable(RpgProgressionState.B_SMALL_POTION_ITEM_ID,s));assertEquals("inventory consumption cannot fake a quickslot action",0,c.count(CampaignProgress.find("T09"),r));for(int n=0;n<800&&s.player().hp>=s.player().maxHp;n++)TownInteriorTest.tick(v,1);assertTrue(s.player().hp<s.player().maxHp);int before=r.inventory().get(RpgProgressionState.B_SMALL_POTION_ITEM_ID);tap(v,821,445);assertEquals(before-1,r.inventory().get(RpgProgressionState.B_SMALL_POTION_ITEM_ID).intValue());assertEquals(CampaignProgress.Status.REPORT,c.status(CampaignProgress.find("T09"),r));capture(v,"quick-potion-real-hp");
 }
 @Test public void acceptedV109LevelElevenSaveKeepsNextQuestGoldExpOwnershipAndCounts()throws Exception{
  GameView v=start("WARRIOR");RuntimeState s=TownInteriorTest.field(v,"state");RpgProgressionState r=s.rpg();r.grantAdaptedReward(378000-CampaignProgress.earnedExp(r),0);JSONObject old=r.campaign().snapshot().put("version",1).put("complete",new JSONArray().put("M01").put("M02").put("M03").put("J01_WARRIOR").put("M04").put("M05").put("M06")).put("active","M07").put("counts",new JSONObject().put("POTE_RED",2));long exp=r.normalExp(),gold=r.gold();assertTrue(r.campaign().restore(old));assertTrue(r.campaign().legacy());assertEquals("M07",r.campaign().next(r).id);assertEquals(2,r.campaign().count(CampaignProgress.find("M07"),r));assertEquals(exp,r.normalExp().longValue());assertEquals(gold,r.gold().longValue());v.pause();F5mSaveStore.install(context);RuntimeState restored=TownInteriorTest.field(new GameView(context),"state");assertTrue(restored.rpg().campaign().legacy());assertEquals("M07",restored.rpg().campaign().next(restored.rpg()).id);assertEquals(2,restored.rpg().campaign().count(CampaignProgress.find("M07"),restored.rpg()));assertEquals(Integer.valueOf(11),restored.rpg().normalLevel());assertEquals(r.equipment(),restored.rpg().equipment());
 }
 @Test public void journalShowsOnlyMyPlayableRouteFocusesCurrentAndExplainsSpecificPrerequisite()throws Exception{
  GameView v=start("MAGE");QuestJournalModel model=TownInteriorTest.field(v,"questJournalModel");RuntimeState s=TownInteriorTest.field(v,"state");List<QuestJournalModel.Row> rows=model.rows(TownInteriorTest.field(v,"f5mQuest"),TownInteriorTest.field(v,"quest2"),false,s.rpg());assertEquals(32,rows.size());assertFalse(rows.stream().anyMatch(r->r.id.contains("WARRIOR")||r.id.equals(QuestJournalModel.FOREST)||r.id.equals("Q_PRO_01")));QuestJournalModel.Row learn=rows.stream().filter(r->r.id.equals("CAMPAIGN_T02")).findFirst().get();assertEquals(QuestJournalModel.Status.LOCKED,learn.status);assertTrue(learn.condition.contains("나에게 맞는 능력치"));tap(v,808,28);QuestJournalWindow window=TownInteriorTest.field(v,"questJournalWindow");assertEquals("CAMPAIGN_T01",window.selected(rows).id);capture(v,"journal-current");tap(v,480,445);assertTrue(window.help);for(int[] step:new int[][]{{0,384},{2,280},{1,280}}){MotionEvent e=MotionEvent.obtain(0,1,step[0],600,step[1],0);v.onTouchEvent(e);e.recycle();}capture(v,"journal-method");float x=s.player().x,y=s.player().y;assertEquals(x,s.player().x,0);assertEquals(y,s.player().y,0);
 }
}
