package com.projectdark.mobile;
import static org.junit.Assert.*;import android.content.Context;import android.graphics.*;import android.view.MotionEvent;import com.projectdark.mobile.world.*;import java.io.*;import java.lang.reflect.*;import java.util.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=34,manifest=Config.NONE) @GraphicsMode(GraphicsMode.Mode.NATIVE)
public class TownInteriorTest {
 Context c;
 @Before public void setup(){c=RuntimeEnvironment.getApplication();c.getSharedPreferences("project_dark_f5m_v1",0).edit().clear().commit();F5mSaveStore.install(c);}
 @SuppressWarnings("unchecked") static <T>T field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return (T)f.get(o);}
 static void call(GameView v,String n)throws Exception{Method m=GameView.class.getDeclaredMethod(n);m.setAccessible(true);m.invoke(v);}
 static void enter(GameView v,TownInteriorDef d)throws Exception{Method m=GameView.class.getDeclaredMethod("enterTownInterior",TownInteriorDef.class);m.setAccessible(true);m.invoke(v,d);}
 static void tick(GameView v,int frames)throws Exception{Method m=GameView.class.getDeclaredMethod("update",float.class);m.setAccessible(true);for(int i=0;i<frames;i++)m.invoke(v,.05f);}
 static void tap(GameView v,float x,float y){MotionEvent e=MotionEvent.obtain(0,0,MotionEvent.ACTION_DOWN,x,y,0);v.onTouchEvent(e);e.recycle();}
 static void capture(GameView v,String n)throws Exception{Bitmap b=Bitmap.createBitmap(960,540,Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));Set<Integer> colors=new HashSet<>();for(int y=100;y<350;y+=3)for(int x=250;x<700;x+=3)colors.add(b.getPixel(x,y));assertTrue("independent scene assets render",colors.size()>100);File f=new File("build/reports/device-review/v88-"+n+".png");f.getParentFile().mkdirs();try(FileOutputStream out=new FileOutputStream(f)){assertTrue(b.compress(Bitmap.CompressFormat.PNG,100,out));}b.recycle();}
 @Test public void denseFurnitureKeepsCustomerAndExitReachableAndAllPropsRenderable(){
  TownInteriorRenderer renderer=new TownInteriorRenderer(c);
  for(TownInteriorDef d:TownInteriorDef.ALL){
   Set<String> visited=new HashSet<>();ArrayDeque<int[]> queue=new ArrayDeque<>();int su=d.kind==TownInteriorDef.Kind.BANK?5:6,sv=d.rows-2;
   queue.add(new int[]{su,sv});visited.add(su+","+sv);
   while(!queue.isEmpty()){int[] q=queue.remove();for(int[] delta:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){int u=q[0]+delta[0],v=q[1]+delta[1];String key=u+","+v;if(u>=1&&u<d.columns&&v>=1&&v<d.rows&&!d.blocked(u,v)&&visited.add(key))queue.add(new int[]{u,v});}}
   assertTrue(d.kind+" customer route",visited.contains(d.customerU+","+d.customerV));assertTrue(d.kind+" exit route",visited.contains(su+","+(d.rows-1)));
   assertTrue(d.kind+" display density",d.props.size()>=13);
   Set<String> solidAnchors=new HashSet<>();for(TownInteriorDef.Prop o:d.props){assertTrue("runtime prop "+o.asset,renderer.hasProp(o.asset));if(o.blocking){assertTrue("unique furniture tile",solidAnchors.add(o.u+","+o.v));assertFalse("NPC remains clear",o.u==d.npcU&&o.v==d.npcV);assertFalse("customer remains clear",o.u==d.customerU&&o.v==d.customerV);}else{assertTrue("raised tabletop detail",o.lift>0);assertTrue("surface decoration has an existing solid support",d.props.stream().anyMatch(base->base.blocking&&base.u==o.u&&base.v==o.v));}}
  }
 }
 @Test public void fourMapsReachNpcUseNativeUiAndExitWithoutPortalLoop()throws Exception{
  for(TownInteriorDef d:TownInteriorDef.ALL){GameView v=new GameView(c);v.layout(0,0,960,540);RuntimeState s=field(v,"state");s.rpg().restoreGold(5000);if(d.kind==TownInteriorDef.Kind.CHURCH)s.player().hp=1;enter(v,d);assertEquals(d.mapId,s.currentMapId());WorldRuntimeAdapter a=field(v,"reagentShopAdapter");assertTrue(new TownInteriorRenderer(c).ready());assertEquals("one empty tile keeps NPC clear of counter",d.npcV+2,d.counterV);for(String outfit:d.outfit.split(",")){EquipmentVisualRegistry.Visual clothing=new EquipmentVisualRegistry(c).get(outfit);assertNotNull("NPC outfit asset "+outfit,clothing);assertNotNull("NPC wearable registration "+outfit,clothing.registration);}assertFalse(a.canPlayerOccupy(d.npcX(),d.npcY()));if(d.kind!=TownInteriorDef.Kind.CHURCH)assertFalse(a.canPlayerOccupy(TownInteriorDef.x(d.npcU,d.counterV),TownInteriorDef.y(d.npcU,d.counterV)));capture(v,d.kind.toString().toLowerCase()+"-map");
   float playerX=s.player().x,playerY=s.player().y;WorldCameraTransform.Point p=a.worldToScreen(d.npcX(),d.npcY());tap(v,p.x,p.y-24);if(d.kind==TownInteriorDef.Kind.INN){assertTrue("distant Mary tap starts a reachable walk",(Boolean)field(v,"merchantApproach"));tick(v,400);assertTrue("approach opens story dialogue, not a shop window",(Boolean)field(v,"innDialogueOpen"));assertFalse(((TownShopWindow)field(v,"townWindow")).isOpen());tap(v,744,321);}else{assertTrue("merchant tap opens its service UI",((TownShopWindow)field(v,"townWindow")).isOpen());assertEquals("NPC tap does not move player",playerX,s.player().x,.01);assertEquals("NPC tap does not move player",playerY,s.player().y,.01);}capture(v,d.kind.toString().toLowerCase()+"-ui");
   if(d.kind!=TownInteriorDef.Kind.INN){long before=s.rpg().gold();tap(v,780,387);assertEquals(before,s.rpg().gold().longValue());capture(v,d.kind.toString().toLowerCase()+"-confirm");tap(v,586,305);assertTrue(s.rpg().gold()<before);if(d.kind==TownInteriorDef.Kind.BANK)assertEquals(1,s.rpg().bankGold());if(d.kind==TownInteriorDef.Kind.CHURCH)assertEquals(s.player().maxHp,s.player().hp);tap(v,895,76);}a.requestGroundWorld(d.exitX(),d.exitY());tick(v,400);assertEquals(WorldDef.ID,s.currentMapId());WorldRuntimeAdapter world=field(v,"worldAdapter");assertNull(world.portalAt(s.player().x,s.player().y));
  }
 }
 @Test public void exteriorDoorsEnterAllFourScenesThroughWorldNavigation()throws Exception{
  for(TownInteriorDef d:TownInteriorDef.ALL){c.getSharedPreferences("project_dark_f5m_v1",0).edit().clear().commit();F5mSaveStore.install(c);GameView v=new GameView(c);v.layout(0,0,960,540);RuntimeState s=field(v,"state");WorldRuntimeAdapter world=field(v,"worldAdapter");MillesDoorAnchors.Door anchor=MillesDoorAnchors.forId(d.doorId);WorldDef.PortalSpawn door=null;for(WorldDef.PortalSpawn p:s.world().portalSpawns())if(d.doorId.equals(p.portalId))door=p;assertNotNull(door);assertEquals(anchor.x,door.x,.001);assertEquals(anchor.y,door.y,.001);assertTrue("walkable threshold "+d.kind,world.canPlayerOccupy(anchor.approachX,anchor.approachY));
   // Native exterior evidence is taken before movement; the route must actually reach the door.
   s.player().x=anchor.approachX;s.player().y=anchor.approachY+96;for(AdaptedMillesIsometricTileLayer.Tile t:AdaptedMillesIsometricTileLayer.tiles())if(Math.abs(t.centerX-anchor.approachX)<1&&Math.abs(t.centerY-(anchor.approachY+96))<1&&world.canPlayerOccupy(t.centerX,t.centerY)){s.player().x=t.centerX;s.player().y=t.centerY;break;}
   world.snapCameraToPlayer();capture(v,d.kind.toString().toLowerCase()+"-exterior-door");world.requestGroundWorld(anchor.approachX,anchor.approachY);tick(v,400);assertEquals("walk through image threshold "+d.kind,d.mapId,s.currentMapId());}
 }
 @Test public void portalMarkersMatchMeasuredBuildingImageThresholds()throws Exception{
  String json;try(InputStream in=c.getAssets().open("maps/milles_garden.json")){json=new String(in.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);}org.json.JSONArray objects=new org.json.JSONObject(json).getJSONArray("objects");
  for(MillesDoorAnchors.Door d:MillesDoorAnchors.ALL){for(int half=0;half<2;half++){org.json.JSONObject marker=null;for(int i=0;i<objects.length();i++){org.json.JSONObject o=objects.getJSONObject(i);if((d.building+"_portal"+(half==0?"":"_2")).equals(o.getString("id")))marker=o;}assertNotNull(d.id+" door half "+half,marker);assertEquals(d.x+half*32,marker.getDouble("x"),.001);assertEquals(d.y+half*16,marker.getDouble("y"),.001);assertEquals("door",marker.getString("draw"));}int count=0;WorldRuntimeAdapter world=new WorldRuntimeAdapter(new RuntimeState(),960,540);for(WorldDef.PortalSpawn spawn:new WorldDef().portalSpawns())if(spawn.portalId.equals(d.id)||spawn.portalId.equals(d.id+"_2")){count++;assertEquals(TownInteriorDef.forDoor(d.id).mapId,spawn.targetMapId);assertTrue("each doorway half is walkable",world.canPlayerOccupy(spawn.x,spawn.y));WorldMapProjection.Portal active=world.portalAt(spawn.x,spawn.y);assertNotNull("door tile resolves to a portal",active);assertEquals("door tiles have independently tappable portal centers",spawn.portalId,active.id);}assertEquals("two traversable door halves",2,count);}
 }
 @Test public void quantityDialogAcceptsOnlyPositiveBoundedNumericInputAndPreservesOriginalExcuranumPixels()throws Exception{assertEquals(27,TownQuantityDialog.parse("27"));assertEquals(-1,TownQuantityDialog.parse("0"));assertEquals(-1,TownQuantityDialog.parse("1000000"));assertEquals(-1,TownQuantityDialog.parse("2a"));ReagentItemVisualRegistry registry=new ReagentItemVisualRegistry(c);Bitmap original;try(InputStream in=c.getAssets().open("assets/items/consumable/it_reagent_excuranum.webp")){original=BitmapFactory.decodeStream(in);}Bitmap rendered=registry.get("IT_REAGENT_EXCURANUM");assertNotNull(rendered);assertEquals(18,rendered.getWidth());assertEquals(24,rendered.getHeight());assertEquals("dark original stopper pixel remains",original.getPixel(9,0),rendered.getPixel(9,0));}
 @Test public void catalogsHaveRegisteredTradableItemsAndExcuranumHeals(){
  RuntimeState s=new RuntimeState();s.rpg().restoreGold(1000000);for(TownInteriorDef.Kind k:new TownInteriorDef.Kind[]{TownInteriorDef.Kind.REAGENT,TownInteriorDef.Kind.EQUIPMENT})for(TownCommerce.Offer o:TownCommerce.offers(k)){assertNotNull(o.id,s.rpg().itemDefinitions().get(o.id));assertEquals(o.id,TownCommerce.Result.OK,TownCommerce.transact(s,k,TownCommerce.Operation.BUY,o.id,1,()->true));}
  assertTrue(TownCommerce.offers(TownInteriorDef.Kind.EQUIPMENT).size()>=17);assertEquals(0,TownCommerce.sellPrice("IT_REAGENT_EXCURANUM"));for(String id:new String[]{"IT_GLOVE_LEATHER","IT_LEGGING_LEATHER","IT_EARRING_DOUBLE_SILVER","IT_RING_REDJADE","IT_RING_THREELINEGOLD","IT_RING_GORU"}){RpgProgressionState.ItemDefinition d=s.rpg().itemDefinitions().get(id);assertNotNull(id,d);assertTrue("Master-backed item has a consistent shop/inventory icon",new SourceItemIconRegistry(RuntimeEnvironment.getApplication()).get(d)!=null);Map<String,Integer> owned=Collections.singletonMap(id,1);Map<String,String> equipped=Collections.singletonMap(d.equipSlot,id);RpgProgressionState check=new RpgProgressionState();assertTrue(check.restoreOwnedItems(owned,equipped));FinalStats stats=check.finalStats();if(id.equals("IT_GLOVE_LEATHER"))assertEquals(-1,stats.ac);if(id.equals("IT_LEGGING_LEATHER"))assertEquals(-2,stats.ac);if(id.equals("IT_EARRING_DOUBLE_SILVER"))assertEquals(4,stats.str);if(id.equals("IT_RING_REDJADE")){assertEquals(200,stats.maxHp);assertEquals(150,stats.maxMp);}if(id.equals("IT_RING_THREELINEGOLD")){assertEquals(-1,stats.ac);assertEquals(400,stats.maxHp);assertEquals(250,stats.maxMp);assertEquals(1,stats.magicDefense);}if(id.equals("IT_RING_GORU"))assertEquals(250,stats.maxMp);}s.player().hp=1;assertEquals(RpgProgressionState.UseResult.USED,s.rpg().useConsumable("IT_REAGENT_EXCURANUM",s));assertEquals(s.player().maxHp,s.player().hp);
 }
 @Test public void transactionsAreConservedAndRollbackEveryChannel(){RuntimeState s=new RuntimeState();RpgProgressionState r=s.rpg();r.restoreGold(2000);String id="IT_TEST_WEAPON_MW002";r.restoreOwnedItems(Collections.emptyMap(),Collections.emptyMap());Map<String,Integer> original=new LinkedHashMap<>(r.inventory());
  assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.BUY,id,3,()->false));assertEquals(original,r.inventory());assertEquals(2000L,r.gold().longValue());
  assertEquals(TownCommerce.Result.OK,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.BUY,id,3,()->true));assertEquals(1100L,r.gold().longValue());assertEquals(Integer.valueOf(3),r.inventory().get(id));
  assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.SELL,id,2,()->false));assertEquals(Integer.valueOf(3),r.inventory().get(id));assertEquals(1100L,r.gold().longValue());
  assertEquals(TownCommerce.Result.OK,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_ITEM,id,2,()->true));assertEquals(Integer.valueOf(1),r.inventory().get(id));assertEquals(Integer.valueOf(2),r.bankInventory().get(id));
  assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.WITHDRAW_ITEM,id,2,()->false));assertEquals(Integer.valueOf(1),r.inventory().get(id));assertEquals(Integer.valueOf(2),r.bankInventory().get(id));
  assertEquals(TownCommerce.Result.OK,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_GOLD,null,1000,()->true));assertEquals(100L,r.gold().longValue());assertEquals(1000,r.bankGold());assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.WITHDRAW_GOLD,null,500,()->false));assertEquals(100L,r.gold().longValue());assertEquals(1000,r.bankGold());
  r.equip(id);assertEquals(TownCommerce.Result.EQUIPPED,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.SELL,id,1,()->true));assertEquals(TownCommerce.Result.NOT_OWNED,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.WITHDRAW_ITEM,id,99,()->true));assertEquals(TownCommerce.Result.INVALID,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.BUY,id,1,()->true));
  s.player().hp=1;assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.CHURCH,TownCommerce.Operation.HEAL,null,1,()->false));assertEquals(1,s.player().hp);assertEquals(100L,r.gold().longValue());
 }
 @Test public void restartRestoresMapCoordinatesGoldStorageAndOwnership()throws Exception{
  for(TownInteriorDef d:TownInteriorDef.ALL){GameView v=new GameView(c);v.layout(0,0,960,540);RuntimeState s=field(v,"state");s.rpg().restoreGold(2000);enter(v,d);String id="IT_REAGENT_CURANUM";TownCommerce.transact(s,TownInteriorDef.Kind.REAGENT,TownCommerce.Operation.BUY,id,2,()->F5mSaveStore.checkpointActive());TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_ITEM,id,1,()->F5mSaveStore.checkpointActive());TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_GOLD,null,100,()->F5mSaveStore.checkpointActive());assertTrue(F5mSaveStore.checkpointActive());float x=s.player().x,y=s.player().y;F5mSaveStore.install(c);GameView restored=new GameView(c);RuntimeState r=field(restored,"state");assertEquals(d.mapId,r.currentMapId());assertEquals(x,r.player().x,.01);assertEquals(y,r.player().y,.01);assertEquals(s.rpg().gold(),r.rpg().gold());assertEquals(s.rpg().bankGold(),r.rpg().bankGold());assertEquals(s.rpg().bankInventory(),r.rpg().bankInventory());assertEquals(s.rpg().inventory(),r.rpg().inventory());assertTrue(F5mSaveStore.writable());call(restored,"leaveReagentShop");}
 }
}
