package com.projectdark.mobile;
import static org.junit.Assert.*;import android.content.Context;import android.graphics.*;import android.view.MotionEvent;import com.projectdark.mobile.world.*;import java.io.*;import java.lang.reflect.*;import java.util.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=34,manifest=Config.NONE) @GraphicsMode(GraphicsMode.Mode.NATIVE)
public class TownInteriorTest {
 Context c;
 @Before public void setup(){c=RuntimeEnvironment.getApplication();c.getSharedPreferences("project_dark_f5m_v1",0).edit().clear().commit();F5mSaveStore.install(c);}
 @SuppressWarnings("unchecked") static <T>T field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return (T)f.get(o);}
 static void call(GameView v,String n)throws Exception{Method m=GameView.class.getDeclaredMethod(n);m.setAccessible(true);m.invoke(v);}
 static void enter(GameView v,TownInteriorDef d)throws Exception{Method m=GameView.class.getDeclaredMethod("enterTownInterior",TownInteriorDef.class);m.setAccessible(true);m.invoke(v,d);}
 static void tick(GameView v,int frames)throws Exception{Method m=GameView.class.getDeclaredMethod("update",float.class);m.setAccessible(true);for(int i=0;i<frames;i++)m.invoke(v,.05f);}
 static void tap(GameView v,float x,float y){MotionEvent e=MotionEvent.obtain(0,0,MotionEvent.ACTION_DOWN,x,y,0);v.onTouchEvent(e);e.recycle();}
 static void capture(GameView v,String n)throws Exception{Bitmap b=Bitmap.createBitmap(960,540,Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));Set<Integer> colors=new HashSet<>();for(int y=100;y<350;y+=3)for(int x=250;x<700;x+=3)colors.add(b.getPixel(x,y));assertTrue("independent scene assets render",colors.size()>100);File f=new File("build/reports/device-review/v85-"+n+".png");f.getParentFile().mkdirs();try(FileOutputStream out=new FileOutputStream(f)){assertTrue(b.compress(Bitmap.CompressFormat.PNG,100,out));}b.recycle();}
 @Test public void fourMapsReachNpcUseNativeUiAndExitWithoutPortalLoop()throws Exception{
  for(TownInteriorDef d:TownInteriorDef.ALL){GameView v=new GameView(c);v.layout(0,0,960,540);RuntimeState s=field(v,"state");s.rpg().restoreGold(5000);if(d.kind==TownInteriorDef.Kind.CHURCH)s.player().hp=1;enter(v,d);assertEquals(d.mapId,s.currentMapId());WorldRuntimeAdapter a=field(v,"reagentShopAdapter");assertTrue(new TownInteriorRenderer(c).ready());for(String outfit:d.outfit.split(",")){EquipmentVisualRegistry.Visual clothing=new EquipmentVisualRegistry(c).get(outfit);assertNotNull("NPC outfit asset "+outfit,clothing);assertNotNull("NPC wearable registration "+outfit,clothing.registration);}assertFalse(a.canPlayerOccupy(d.npcX(),d.npcY()));if(d.kind!=TownInteriorDef.Kind.CHURCH)assertFalse(a.canPlayerOccupy(TownInteriorDef.x(d.npcU,d.counterV),TownInteriorDef.y(d.npcU,d.counterV)));capture(v,d.kind.toString().toLowerCase()+"-map");
   WorldCameraTransform.Point p=a.worldToScreen(d.npcX(),d.npcY());tap(v,p.x,p.y-24);assertFalse(((TownShopWindow)field(v,"townWindow")).isOpen());tick(v,400);assertEquals(d.customerX(),s.player().x,.01);assertEquals(d.customerY(),s.player().y,.01);assertTrue(((TownShopWindow)field(v,"townWindow")).isOpen());capture(v,d.kind.toString().toLowerCase()+"-ui");
   long before=s.rpg().gold();tap(v,780,387);assertEquals(before,s.rpg().gold().longValue());capture(v,d.kind.toString().toLowerCase()+"-confirm");tap(v,586,305);assertTrue(s.rpg().gold()<before);if(d.kind==TownInteriorDef.Kind.BANK)assertEquals(1,s.rpg().bankGold());if(d.kind==TownInteriorDef.Kind.CHURCH)assertEquals(s.player().maxHp,s.player().hp);tap(v,895,76);a.requestGroundWorld(d.exitX(),d.exitY());tick(v,400);assertEquals(WorldDef.ID,s.currentMapId());WorldRuntimeAdapter world=field(v,"worldAdapter");assertNull(world.portalAt(s.player().x,s.player().y));
  }
 }
 @Test public void exteriorDoorsEnterAllFourScenesThroughWorldNavigation()throws Exception{
  for(TownInteriorDef d:TownInteriorDef.ALL){c.getSharedPreferences("project_dark_f5m_v1",0).edit().clear().commit();F5mSaveStore.install(c);GameView v=new GameView(c);v.layout(0,0,960,540);RuntimeState s=field(v,"state");WorldRuntimeAdapter world=field(v,"worldAdapter");MillesDoorAnchors.Door anchor=MillesDoorAnchors.forId(d.doorId);WorldDef.PortalSpawn door=null;for(WorldDef.PortalSpawn p:s.world().portalSpawns())if(d.doorId.equals(p.portalId))door=p;assertNotNull(door);assertEquals(anchor.x,door.x,.001);assertEquals(anchor.y,door.y,.001);assertTrue("walkable threshold "+d.kind,world.canPlayerOccupy(anchor.approachX,anchor.approachY));
   // Native exterior evidence is taken before movement; the route must actually reach the door.
   s.player().x=anchor.approachX;s.player().y=anchor.approachY+96;for(AdaptedMillesIsometricTileLayer.Tile t:AdaptedMillesIsometricTileLayer.tiles())if(Math.abs(t.centerX-anchor.approachX)<1&&Math.abs(t.centerY-(anchor.approachY+96))<1&&world.canPlayerOccupy(t.centerX,t.centerY)){s.player().x=t.centerX;s.player().y=t.centerY;break;}
   world.snapCameraToPlayer();capture(v,d.kind.toString().toLowerCase()+"-exterior-door");world.requestGroundWorld(anchor.approachX,anchor.approachY);tick(v,400);assertEquals("walk through image threshold "+d.kind,d.mapId,s.currentMapId());}
 }
 @Test public void catalogsHaveRegisteredTradableItemsAndExcuranumHeals(){
  RuntimeState s=new RuntimeState();s.rpg().restoreGold(1000000);for(TownInteriorDef.Kind k:new TownInteriorDef.Kind[]{TownInteriorDef.Kind.REAGENT,TownInteriorDef.Kind.EQUIPMENT})for(TownCommerce.Offer o:TownCommerce.offers(k)){assertNotNull(o.id,s.rpg().itemDefinitions().get(o.id));assertEquals(o.id,TownCommerce.Result.OK,TownCommerce.transact(s,k,TownCommerce.Operation.BUY,o.id,1,()->true));}
  assertTrue(TownCommerce.offers(TownInteriorDef.Kind.EQUIPMENT).size()>=17);assertEquals(0,TownCommerce.sellPrice("IT_REAGENT_EXCURANUM"));s.player().hp=1;assertEquals(RpgProgressionState.UseResult.USED,s.rpg().useConsumable("IT_REAGENT_EXCURANUM",s));assertEquals(s.player().maxHp,s.player().hp);
 }
 @Test public void transactionsAreConservedAndRollbackEveryChannel(){RuntimeState s=new RuntimeState();RpgProgressionState r=s.rpg();r.restoreGold(2000);String id="IT_TEST_WEAPON_MW002";r.restoreOwnedItems(Collections.emptyMap(),Collections.emptyMap());Map<String,Integer> original=new LinkedHashMap<>(r.inventory());
  assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.BUY,id,3,()->false));assertEquals(original,r.inventory());assertEquals(2000L,r.gold().longValue());
  assertEquals(TownCommerce.Result.OK,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.BUY,id,3,()->true));assertEquals(1100L,r.gold().longValue());assertEquals(Integer.valueOf(3),r.inventory().get(id));
  assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.SELL,id,2,()->false));assertEquals(Integer.valueOf(3),r.inventory().get(id));assertEquals(1100L,r.gold().longValue());
  assertEquals(TownCommerce.Result.OK,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_ITEM,id,2,()->true));assertEquals(Integer.valueOf(1),r.inventory().get(id));assertEquals(Integer.valueOf(2),r.bankInventory().get(id));
  assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.WITHDRAW_ITEM,id,2,()->false));assertEquals(Integer.valueOf(1),r.inventory().get(id));assertEquals(Integer.valueOf(2),r.bankInventory().get(id));
  assertEquals(TownCommerce.Result.OK,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_GOLD,null,1000,()->true));assertEquals(100L,r.gold().longValue());assertEquals(1000,r.bankGold());assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.WITHDRAW_GOLD,null,500,()->false));assertEquals(100L,r.gold().longValue());assertEquals(1000,r.bankGold());
  r.equip(id);assertEquals(TownCommerce.Result.EQUIPPED,TownCommerce.transact(s,TownInteriorDef.Kind.EQUIPMENT,TownCommerce.Operation.SELL,id,1,()->true));assertEquals(TownCommerce.Result.NOT_OWNED,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.WITHDRAW_ITEM,id,99,()->true));assertEquals(TownCommerce.Result.INVALID,TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.BUY,id,1,()->true));
  s.player().hp=1;assertEquals(TownCommerce.Result.SAVE_FAILED,TownCommerce.transact(s,TownInteriorDef.Kind.CHURCH,TownCommerce.Operation.HEAL,null,1,()->false));assertEquals(1,s.player().hp);assertEquals(100L,r.gold().longValue());
 }
 @Test public void restartRestoresMapCoordinatesGoldStorageAndOwnership()throws Exception{
  for(TownInteriorDef d:TownInteriorDef.ALL){GameView v=new GameView(c);v.layout(0,0,960,540);RuntimeState s=field(v,"state");s.rpg().restoreGold(2000);enter(v,d);String id="IT_REAGENT_CURANUM";TownCommerce.transact(s,TownInteriorDef.Kind.REAGENT,TownCommerce.Operation.BUY,id,2,()->F5mSaveStore.checkpointActive());TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_ITEM,id,1,()->F5mSaveStore.checkpointActive());TownCommerce.transact(s,TownInteriorDef.Kind.BANK,TownCommerce.Operation.DEPOSIT_GOLD,null,100,()->F5mSaveStore.checkpointActive());assertTrue(F5mSaveStore.checkpointActive());float x=s.player().x,y=s.player().y;F5mSaveStore.install(c);GameView restored=new GameView(c);RuntimeState r=field(restored,"state");assertEquals(d.mapId,r.currentMapId());assertEquals(x,r.player().x,.01);assertEquals(y,r.player().y,.01);assertEquals(s.rpg().gold(),r.rpg().gold());assertEquals(s.rpg().bankGold(),r.rpg().bankGold());assertEquals(s.rpg().bankInventory(),r.rpg().bankInventory());assertEquals(s.rpg().inventory(),r.rpg().inventory());assertTrue(F5mSaveStore.writable());call(restored,"leaveReagentShop");}
 }
}
