#!/usr/bin/env python3
"""Generate only accepted, field-evidenced numeric equipment projections."""
import csv, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
assert json.loads((ROOT/'master/changes/EQUIPMENT-FOUNDATION-V124.json').read_text())['status']=='ACCEPTED'
rows=list(csv.DictReader((ROOT/'master/canonical/Equipment_Stats.csv').open()))
receipts={(r['Item_ID'],r['Field'],r['Value']) for r in csv.DictReader((ROOT/'master/canonical/Item_Evidence.csv').open()) if r['Status']=='ACCEPTED'}
keys=['MinATK','MaxATK','AC','HIT','DAM','HP','MP','STR','INT','WIS','CON','DEX','MagicDefense']
lines=['package com.projectdark.mobile;','import java.util.*;','/** Generated by tools/generate_equipment_stats.py; source/era receipts in Master. */','final class SourceEquipmentStats {',' private SourceEquipmentStats(){}',' static Map<String,Integer> forItem(String id){','  Map<String,Integer> m=new LinkedHashMap<>();','  switch(id){']
for r in rows:
    lines.append('   case '+json.dumps(r['Item_ID'])+':')
    for k in keys:
        if r[k]=='': continue
        assert (r['Item_ID'],k,r[k]) in receipts,(r['Item_ID'],k)
        key='MAGIC_DEFENSE' if k=='MagicDefense' else k
        lines.append(f'    m.put("{key}",{int(r[k])});')
    lines.append('    return m;')
lines+=['   default:return null;','  }',' }','}']
(ROOT/'app/src/main/java/com/projectdark/mobile/SourceEquipmentStats.java').write_text('\n'.join(lines)+'\n')
print('SOURCE_EQUIPMENT_STATS',len(rows),'field-evidenced items')
